all:  VelocDecayAnalysisTG_const_dt VelocProfileComparisonTG

VelocProfileComparisonTG: VelocProfileComparisonTG.cpp

VelocDecayAnalysisTG_const_dt: VelocDecayAnalysisTG_const_dt.cpp


.PHONY: clean

clean:
	-rm exactResAndErrTG
	-rm VelocDecayAnalysisTG_const_dt


