
# all:  VelocDecayAnalysisTG_const_dt VelocProfileComparisonTG VelocDecayAnalysisTGautomFileRecognition

# VelocProfileComparisonTG: VelocProfileComparisonTG.cpp

VelocDecayAnalysisTG_const_dt: VelocDecayAnalysisTG_const_dt.cpp

# VelocDecayAnalysisTGautomFileRecognition: VelocDecayAnalysisTGautomFileRecognition.cpp


.PHONY: clean

clean:
#	-rm exactResAndErrTG
	-rm VelocDecayAnalysisTG_const_dt
#	-rm VelocDecayAnalysisTGautomFileRecognition


