all: findPeakVelocitiesOscillation findPeakVelocitiesTravelWave

findPeakVelocitiesOscillation: findPeakVelocitiesOscillation.cpp

findPeakVelocitiesTravelWave: findPeakVelocitiesTravelWave.cpp



.PHONY: clean

clean:
	-rm findPeakVelocitiesOscillation
	-rm findPeakVelocitiesTravelWave
