
 all: exactResAndErrPoiseuille exactResAndErrThermalBC

exactResAndErrPoiseuille: exactResAndErrPoiseuille.cpp
exactResAndErrThermalBC: exactResAndErrThermalBC.cpp



.PHONY: clean

clean:
	-rm exactResAndErrPoiseuille
	-rm exactResAndErrThermalBC

