
 all: exactResAndErrPoiseuille exactResAndErrThermalBC timeInterpolation

exactResAndErrPoiseuille: exactResAndErrPoiseuille.cpp
exactResAndErrThermalBC: exactResAndErrThermalBC.cpp
timeInterpolation: timeInterpolation.cpp



.PHONY: clean

clean:
	-rm exactResAndErrPoiseuille
	-rm exactResAndErrThermalBC
	-rm timeInterpolation

