all: average_q1DResults exactResAndErr1DST exactResAndErr1DST2\
	exactResAndErr1DST2 average_q1DResultsRAND

average_q1DResults: average_q1DResults.cpp

average_q1DResultsRAND: average_q1DResultsRAND.cpp

exactResAndErr1DST: exactResAndErr1DST.cpp 

exactResAndErr1DST2: exactResAndErr1DST2.cpp

exactResAndErr1DST3: exactResAndErr1DST3.cpp

.PHONY: clean

clean:
	-rm average_q1DResults
	-rm exactResAndErr1DST
	-rm exactResAndErr1DST2
	-rm exactResAndErr1DST3
	-rm average_q1DResultsRAND
