all: average_q1DResults exactResAndErr1DST average_q1DResultsRAND

average_q1DResults: average_q1DResults.cpp

average_q1DResultsRAND: average_q1DResultsRAND.cpp

exactResAndErr1DST: exactResAndErr1DST.cpp 

.PHONY: clean

clean:
	-rm average_q1DResults
	-rm exactResAndErr1DST
	-rm average_q1DResultsRAND
