all: create_ICCavity create_ICLinearWall_Poiseuille_domainEdgeBC

create_ICCavity: create_ICCavity.cpp

create_ICLinearWall_Poiseuille_domainEdgeBC: create_ICLinearWall_Poiseuille_domainEdgeBC.cpp

.PHONY: clean

clean:
	-rm create_ICCavity
	-rm create_ICLinearWall_Poiseuille_domainEdgeBC
