all: createIC_PureHeatConduction createIC_PureHeatConductionOWR



createIC_PureHeatConduction: createIC_PureHeatConduction.cpp

createIC_PureHeatConductionOWR: createIC_PureHeatConductionOWR.cpp

.PHONY: clean

clean:
	-rm createIC_PureHeatConduction
	-rm createIC_PureHeatConductionOWR
