blitz: Beta< T, IRNG, stateTag > Class Template Reference
Beta< T, IRNG, stateTag > Class Template Reference
#include <beta.h>
Public Types
typedef T T_numtype
Public Member Functions
Beta (T a, T b)
Beta (T a, T b, unsigned int i)
T random ()
void setParameters (T a, T b)
Protected Member Functions
T ranf ()
Protected Attributes
T aa
T bb
T infnty
T minlog
T expmax
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState>
class Beta< T, IRNG, stateTag >
Member Typedef Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> typedef T Beta< T, IRNG, stateTag >::T_numtype
Reimplemented from UniformOpen< T, IRNG, stateTag >.
Constructor & Destructor Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> Beta< T, IRNG, stateTag >::Beta (T a, T b) [inline]
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> Beta< T, IRNG, stateTag >::Beta (T a, T b, unsigned int i) [inline]
Member Function Documentation
template<typename T , typename IRNG , typename stateTag > T Beta< T, IRNG, stateTag >::random (void) [inline]
Reimplemented from UniformOpen< T, IRNG, stateTag >.
References a, Beta< T, IRNG, stateTag >::aa, Beta< T, IRNG, stateTag >::bb, Beta< T, IRNG, stateTag >::expmax, Beta< T, IRNG, stateTag >::infnty, Beta< T, IRNG, stateTag >::minlog, r, Beta< T, IRNG, stateTag >::ranf(), s, and t.
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Beta< T, IRNG, stateTag >::ranf () [inline, protected]
References UniformOpen< T, IRNG, stateTag >::random().
Referenced by Beta< T, IRNG, stateTag >::random().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> void Beta< T, IRNG, stateTag >::setParameters (T a, T b) [inline]
Member Data Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Beta< T, IRNG, stateTag >::aa [protected]
Referenced by Beta< T, IRNG, stateTag >::random().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Beta< T, IRNG, stateTag >::bb [protected]
Referenced by Beta< T, IRNG, stateTag >::random().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Beta< T, IRNG, stateTag >::expmax [protected]
Referenced by Beta< T, IRNG, stateTag >::random().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Beta< T, IRNG, stateTag >::infnty [protected]
Referenced by Beta< T, IRNG, stateTag >::random().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Beta< T, IRNG, stateTag >::minlog [protected]
Referenced by Beta< T, IRNG, stateTag >::random().
The documentation for this class was generated from the following file:
random/beta.h