blitz: RowMajor Class Reference
RowMajor Class Reference
#include <matgen.h>
Public Types
typedef RowMajorIterator T_iterator
Public Member Functions
RowMajor ()
RowMajor (unsigned rows, unsigned cols)
unsigned coordToOffset (unsigned i, unsigned j) const
template<typename T_numtype >
T_numtype get (const T_numtype *restrict data, unsigned i, unsigned j) const
template<typename T_numtype >
T_numtype & get (T_numtype *restrict data, unsigned i, unsigned j)
Member Typedef Documentation
typedef RowMajorIterator RowMajor::T_iterator
Constructor & Destructor Documentation
RowMajor::RowMajor () [inline]
RowMajor::RowMajor (unsigned rows, unsigned cols) [inline]
Member Function Documentation
unsigned RowMajor::coordToOffset (unsigned i, unsigned j) const [inline]
References AsymmetricMatrix::cols_.
Referenced by get().
template<typename T_numtype > T_numtype& RowMajor::get (T_numtype *restrict data, unsigned i, unsigned j) [inline]
References coordToOffset(), i, AsymmetricMatrix::inRange(), and j.
template<typename T_numtype > T_numtype RowMajor::get (const T_numtype *restrict data, unsigned i, unsigned j) const [inline]
References coordToOffset(), i, AsymmetricMatrix::inRange(), and j.
The documentation for this class was generated from the following file:
blitz/matgen.h