blitz: MemoryBlockReference< P_type > Class Template Reference
MemoryBlockReference< P_type > Class Template Reference
#include <memblock.h>
Public Types
typedef P_type T_type
Public Member Functions
MemoryBlockReference ()
MemoryBlockReference (MemoryBlockReference< T_type > &ref, sizeType offset=0)
MemoryBlockReference (sizeType length, T_type *data, preexistingMemoryPolicy deletionPolicy)
MemoryBlockReference (sizeType items)
~MemoryBlockReference ()
Protected Member Functions
int numReferences () const
bool lockReferenceCount (bool lockingPolicy) const
void changeToNullBlock ()
void changeBlock (MemoryBlockReference< T_type > &ref, sizeType offset=0)
void newBlock (sizeType items)
Protected Attributes
T_type *restrict data_
Private Member Functions
void blockRemoveReference ()
void addReference () const
int removeReference () const
void operator= (const MemoryBlockReference< T_type > &)
Private Attributes
MemoryBlock< T_type > * block_
template<typename P_type>
class MemoryBlockReference< P_type >
Member Typedef Documentation
template<typename P_type> typedef P_type MemoryBlockReference< P_type >::T_type
Constructor & Destructor Documentation
template<typename P_type> MemoryBlockReference< P_type >::MemoryBlockReference () [inline]
template<typename P_type> MemoryBlockReference< P_type >::MemoryBlockReference (MemoryBlockReference< T_type > & ref, sizeType offset = 0) [inline]
template<typename P_type> MemoryBlockReference< P_type >::MemoryBlockReference (sizeType length, T_type * data, preexistingMemoryPolicy deletionPolicy) [inline]
template<typename P_type> MemoryBlockReference< P_type >::MemoryBlockReference (sizeType items) [inline, explicit]
template<typename P_type> MemoryBlockReference< P_type >::~MemoryBlockReference () [inline]
Member Function Documentation
template<typename P_type> void MemoryBlockReference< P_type >::addReference () const [inline, private]
template<typename P_type> void MemoryBlockReference< P_type >::blockRemoveReference () [inline, private]
Referenced by MemoryBlockReference< int >::changeBlock(), MemoryBlockReference< int >::changeToNullBlock(), MemoryBlockReference< int >::newBlock(), and MemoryBlockReference< int >::~MemoryBlockReference().
template<typename P_type> void MemoryBlockReference< P_type >::changeBlock (MemoryBlockReference< T_type > & ref, sizeType offset = 0) [inline, protected]
template<typename P_type> void MemoryBlockReference< P_type >::changeToNullBlock () [inline, protected]
template<typename P_type> bool MemoryBlockReference< P_type >::lockReferenceCount (bool lockingPolicy) const [inline, protected]
template<typename P_type> void MemoryBlockReference< P_type >::newBlock (sizeType items) [inline, protected]
Referenced by Matrix< P_numtype, BZ_TEMPLATE_DEFAULT >::Matrix(), and Matrix< P_numtype, BZ_TEMPLATE_DEFAULT >::resize().
template<typename P_type> int MemoryBlockReference< P_type >::numReferences () const [inline, protected]
template<typename P_type> void MemoryBlockReference< P_type >::operator= (const MemoryBlockReference< T_type > &) [inline, private]
template<typename P_type> int MemoryBlockReference< P_type >::removeReference () const [inline, private]
Member Data Documentation
template<typename P_type> MemoryBlock<T_type>* MemoryBlockReference< P_type >::block_ [private]
Referenced by MemoryBlockReference< int >::changeBlock(), and MemoryBlockReference< int >::MemoryBlockReference().
template<typename P_type> T_type* restrict MemoryBlockReference< P_type >::data_ [protected]
Referenced by MemoryBlockReference< int >::changeBlock(), and MemoryBlockReference< int >::MemoryBlockReference().
The documentation for this class was generated from the following file:
blitz/memblock.h