blitz: Array< P_numtype, N_rank > Class Template Reference
Array< P_numtype, N_rank > Class Template Reference
#include <array-impl.h>
Public Types
typedef P_numtype T_numtype
typedef TinyVector< int, N_rank > T_index
typedef Array< T_numtype, N_rank > T_array
typedef FastArrayIterator
< T_numtype, N_rank > T_iterator
typedef ArrayIterator
< T_numtype, N_rank > iterator
typedef ConstArrayIterator
< T_numtype, N_rank > const_iterator
Public Member Functions
template<typename T_expr >
Array (_bz_ArrayExpr< T_expr > expr)
Array (GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (int length0, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (int length0, int length1, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (int length0, int length1, int length2, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (int length0, int length1, int length2, int length3, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (int length0, int length1, int length2, int length3, int length4, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (int length0, int length1, int length2, int length3, int length4, int length5, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (int length0, int length1, int length2, int length3, int length4, int length5, int length6, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (int length0, int length1, int length2, int length3, int length4, int length5, int length6, int length7, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (int length0, int length1, int length2, int length3, int length4, int length5, int length6, int length7, int length8, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (int length0, int length1, int length2, int length3, int length4, int length5, int length6, int length7, int length8, int length9, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (int length0, int length1, int length2, int length3, int length4, int length5, int length6, int length7, int length8, int length9, int length10, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (T_numtype *restrict dataFirst, TinyVector< int, N_rank > shape, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (T_numtype *restrict dataFirst, TinyVector< int, N_rank > shape, TinyVector< diffType, N_rank > stride, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (T_numtype *restrict dataFirst, TinyVector< int, N_rank > shape, preexistingMemoryPolicy deletionPolicy, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (T_numtype *restrict dataFirst, TinyVector< int, N_rank > shape, TinyVector< diffType, N_rank > stride, preexistingMemoryPolicy deletionPolicy, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (const TinyVector< int, N_rank > &extent, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (const TinyVector< int, N_rank > &lbounds, const TinyVector< int, N_rank > &extent, const GeneralArrayStorage< N_rank > &storage=GeneralArrayStorage< N_rank >())
Array (Range r0, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (Range r0, Range r1, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (Range r0, Range r1, Range r2, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (Range r0, Range r1, Range r2, Range r3, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (Range r0, Range r1, Range r2, Range r3, Range r4, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10, GeneralArrayStorage< N_rank > storage=GeneralArrayStorage< N_rank >())
Array (const Array< T_numtype, N_rank > &array)
Array (const TinyVector< int, N_rank-1 > &shape, int lastExtent, const GeneralArrayStorage< N_rank > &storage)
Array (Array< T_numtype, N_rank > &array, Range r0)
Array (Array< T_numtype, N_rank > &array, Range r0, Range r1)
Array (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2)
Array (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3)
Array (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4)
Array (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5)
Array (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6)
Array (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7)
Array (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8)
Array (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9)
Array (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10)
Array (Array< T_numtype, N_rank > &array, const RectDomain< N_rank > &subdomain)
Array (Array< T_numtype, N_rank > &array, const StridedDomain< N_rank > &subdomain)
template<int N_rank2, typename R0 , typename R1 , typename R2 , typename R3 , typename R4 , typename R5 , typename R6 , typename R7 , typename R8 , typename R9 , typename R10 >
Array (Array< T_numtype, N_rank2 > &array, R0 r0, R1 r1, R2 r2, R3 r3, R4 r4, R5 r5, R6 r6, R7 r7, R8 r8, R9 r9, R10 r10)
const TinyVector< int, N_rank > & base () const
int base (int rank) const
iterator begin ()
const_iterator begin () const
T_iterator beginFast () const
template<typename P_numtype2 >
Array< P_numtype2, N_rank > chopComponent (P_numtype2 a, int compNum, int numComponents) const
int cols () const
int columns () const
T_array copy () const
diffType dataOffset () const
const T_numtype *restrict data () const
T_numtype *restrict data ()
const T_numtype *restrict dataZero () const
T_numtype *restrict dataZero ()
diffType dataFirstOffset () const
const T_numtype *restrict dataFirst () const
T_numtype *restrict dataFirst ()
int depth () const
int dimensions () const
RectDomain< N_rank > domain () const
void dumpStructureInformation (ostream &os=cout) const
iterator end ()
const_iterator end () const
int extent (int rank) const
const TinyVector< int, N_rank > & extent () const
template<typename P_numtype2 >
Array< P_numtype2, N_rank > extractComponent (P_numtype2, int compNum, int numComponents) const
void free ()
bool isMajorRank (int rank) const
bool isMinorRank (int rank) const
bool isRankStoredAscending (int rank) const
bool isStorageContiguous () const
int lbound (int rank) const
TinyVector< int, N_rank > lbound () const
int length (int rank) const
const TinyVector< int, N_rank > & length () const
void makeUnique ()
sizeType numElements () const
int ordering (int storageRankIndex) const
const TinyVector< int, N_rank > & ordering () const
void transposeSelf (int r0, int r1, int r2=0, int r3=0, int r4=0, int r5=0, int r6=0, int r7=0, int r8=0, int r9=0, int r10=0)
T_array transpose (int r0, int r1, int r2=0, int r3=0, int r4=0, int r5=0, int r6=0, int r7=0, int r8=0, int r9=0, int r10=0) const
int rank () const
void reference (const T_array &)
void weakReference (const T_array &)
T_array reindex (const TinyVector< int, N_rank > &)
void reindexSelf (const TinyVector< int, N_rank > &)
void resize (int extent)
void resize (int extent1, int extent2)
void resize (int extent1, int extent2, int extent3)
void resize (int extent1, int extent2, int extent3, int extent4)
void resize (int extent1, int extent2, int extent3, int extent4, int extent5)
void resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6)
void resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7)
void resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8)
void resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9)
void resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9, int extent10)
void resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9, int extent10, int extent11)
void resize (Range r1)
void resize (Range r1, Range r2)
void resize (Range r1, Range r2, Range r3)
void resize (Range r1, Range r2, Range r3, Range r4)
void resize (Range r1, Range r2, Range r3, Range r4, Range r5)
void resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6)
void resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7)
void resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8)
void resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9)
void resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10)
void resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10, Range r11)
void resize (const TinyVector< int, N_rank > &)
void resizeAndPreserve (const TinyVector< int, N_rank > &)
void resizeAndPreserve (int extent)
void resizeAndPreserve (int extent1, int extent2)
void resizeAndPreserve (int extent1, int extent2, int extent3)
void resizeAndPreserve (int extent1, int extent2, int extent3, int extent4)
void resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5)
void resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6)
void resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7)
void resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8)
void resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9)
void resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9, int extent10)
void resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9, int extent10, int extent11)
T_array reverse (int rank)
void reverseSelf (int rank)
int rows () const
void setStorage (GeneralArrayStorage< N_rank >)
void slice (int rank, Range r)
const TinyVector< int, N_rank > & shape () const
sizeType size () const
const TinyVector< diffType,
N_rank > & stride () const
diffType stride (int rank) const
bool threadLocal (bool disableLock=true) const
int ubound (int rank) const
TinyVector< int, N_rank > ubound () const
int zeroOffset () const
bool isInRangeForDim (int i, int d) const
bool isInRange (int i0) const
bool isInRange (int i0, int i1) const
bool isInRange (int i0, int i1, int i2) const
bool isInRange (int i0, int i1, int i2, int i3) const
bool isInRange (int i0, int i1, int i2, int i3, int i4) const
bool isInRange (int i0, int i1, int i2, int i3, int i4, int i5) const
bool isInRange (int i0, int i1, int i2, int i3, int i4, int i5, int i6) const
bool isInRange (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7) const
bool isInRange (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8) const
bool isInRange (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9) const
bool isInRange (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10) const
bool isInRange (const T_index &index) const
bool assertInRange (const T_index &BZ_DEBUG_PARAM(index)) const
bool assertInRange (int BZ_DEBUG_PARAM(i0)) const
bool assertInRange (int BZ_DEBUG_PARAM(i0), int BZ_DEBUG_PARAM(i1)) const
bool assertInRange (int BZ_DEBUG_PARAM(i0), int BZ_DEBUG_PARAM(i1), int BZ_DEBUG_PARAM(i2)) const
bool assertInRange (int BZ_DEBUG_PARAM(i0), int BZ_DEBUG_PARAM(i1), int BZ_DEBUG_PARAM(i2), int BZ_DEBUG_PARAM(i3)) const
bool assertInRange (int BZ_DEBUG_PARAM(i0), int BZ_DEBUG_PARAM(i1), int BZ_DEBUG_PARAM(i2), int BZ_DEBUG_PARAM(i3), int BZ_DEBUG_PARAM(i4)) const
bool assertInRange (int BZ_DEBUG_PARAM(i0), int BZ_DEBUG_PARAM(i1), int BZ_DEBUG_PARAM(i2), int BZ_DEBUG_PARAM(i3), int BZ_DEBUG_PARAM(i4), int BZ_DEBUG_PARAM(i5)) const
bool assertInRange (int BZ_DEBUG_PARAM(i0), int BZ_DEBUG_PARAM(i1), int BZ_DEBUG_PARAM(i2), int BZ_DEBUG_PARAM(i3), int BZ_DEBUG_PARAM(i4), int BZ_DEBUG_PARAM(i5), int BZ_DEBUG_PARAM(i6)) const
bool assertInRange (int BZ_DEBUG_PARAM(i0), int BZ_DEBUG_PARAM(i1), int BZ_DEBUG_PARAM(i2), int BZ_DEBUG_PARAM(i3), int BZ_DEBUG_PARAM(i4), int BZ_DEBUG_PARAM(i5), int BZ_DEBUG_PARAM(i6), int BZ_DEBUG_PARAM(i7)) const
bool assertInRange (int BZ_DEBUG_PARAM(i0), int BZ_DEBUG_PARAM(i1), int BZ_DEBUG_PARAM(i2), int BZ_DEBUG_PARAM(i3), int BZ_DEBUG_PARAM(i4), int BZ_DEBUG_PARAM(i5), int BZ_DEBUG_PARAM(i6), int BZ_DEBUG_PARAM(i7), int BZ_DEBUG_PARAM(i8)) const
bool assertInRange (int BZ_DEBUG_PARAM(i0), int BZ_DEBUG_PARAM(i1), int BZ_DEBUG_PARAM(i2), int BZ_DEBUG_PARAM(i3), int BZ_DEBUG_PARAM(i4), int BZ_DEBUG_PARAM(i5), int BZ_DEBUG_PARAM(i6), int BZ_DEBUG_PARAM(i7), int BZ_DEBUG_PARAM(i8), int BZ_DEBUG_PARAM(i9)) const
bool assertInRange (int BZ_DEBUG_PARAM(i0), int BZ_DEBUG_PARAM(i1), int BZ_DEBUG_PARAM(i2), int BZ_DEBUG_PARAM(i3), int BZ_DEBUG_PARAM(i4), int BZ_DEBUG_PARAM(i5), int BZ_DEBUG_PARAM(i6), int BZ_DEBUG_PARAM(i7), int BZ_DEBUG_PARAM(i8), int BZ_DEBUG_PARAM(i9), int BZ_DEBUG_PARAM(i10)) const
template<int N_rank2>
const T_numtype &restrict operator() (const TinyVector< int, N_rank2 > &index) const
template<int N_rank2>
T_numtype &restrict operator() (const TinyVector< int, N_rank2 > &index)
const T_numtype &restrict operator() (TinyVector< int, 1 > index) const
T_numtype & operator() (TinyVector< int, 1 > index)
const T_numtype &restrict operator() (TinyVector< int, 2 > index) const
T_numtype & operator() (TinyVector< int, 2 > index)
const T_numtype &restrict operator() (TinyVector< int, 3 > index) const
T_numtype & operator() (TinyVector< int, 3 > index)
const T_numtype &restrict operator() (const TinyVector< int, 4 > &index) const
T_numtype & operator() (const TinyVector< int, 4 > &index)
const T_numtype &restrict operator() (const TinyVector< int, 5 > &index) const
T_numtype & operator() (const TinyVector< int, 5 > &index)
const T_numtype &restrict operator() (const TinyVector< int, 6 > &index) const
T_numtype & operator() (const TinyVector< int, 6 > &index)
const T_numtype &restrict operator() (const TinyVector< int, 7 > &index) const
T_numtype & operator() (const TinyVector< int, 7 > &index)
const T_numtype &restrict operator() (const TinyVector< int, 8 > &index) const
T_numtype & operator() (const TinyVector< int, 8 > &index)
const T_numtype &restrict operator() (const TinyVector< int, 9 > &index) const
T_numtype & operator() (const TinyVector< int, 9 > &index)
const T_numtype &restrict operator() (const TinyVector< int, 10 > &index) const
T_numtype & operator() (const TinyVector< int, 10 > &index)
const T_numtype &restrict operator() (const TinyVector< int, 11 > &index) const
T_numtype & operator() (const TinyVector< int, 11 > &index)
const T_numtype &restrict operator() (int i0) const
T_numtype &restrict operator() (int i0)
const T_numtype &restrict operator() (int i0, int i1) const
T_numtype &restrict operator() (int i0, int i1)
const T_numtype &restrict operator() (int i0, int i1, int i2) const
T_numtype &restrict operator() (int i0, int i1, int i2)
const T_numtype &restrict operator() (int i0, int i1, int i2, int i3) const
T_numtype &restrict operator() (int i0, int i1, int i2, int i3)
const T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4) const
T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4)
const T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5) const
T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5)
const T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6) const
T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6)
const T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7) const
T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7)
const T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8) const
T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8)
const T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9) const
T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9)
const T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10) const
T_numtype &restrict operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10)
T_array & noConst () const
T_array operator() (const RectDomain< N_rank > &subdomain) const
T_array operator() (const StridedDomain< N_rank > &subdomain) const
T_array operator() (Range r0) const
T_array operator() (Range r0, Range r1) const
T_array operator() (Range r0, Range r1, Range r2) const
T_array operator() (Range r0, Range r1, Range r2, Range r3) const
T_array operator() (Range r0, Range r1, Range r2, Range r3, Range r4) const
T_array operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5) const
T_array operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6) const
T_array operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7) const
T_array operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8) const
T_array operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9) const
T_array operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10) const
template<int N0>
_bz_ArrayExpr
< ArrayIndexMapping
< FastArrayIterator< T_numtype,
N_rank >, N0 > > operator() (IndexPlaceholder< N0 >) const
template<int N0, int N1>
_bz_ArrayExpr
< ArrayIndexMapping
< FastArrayIterator< T_numtype,
N_rank >, N0, N1 > > operator() (IndexPlaceholder< N0 >, IndexPlaceholder< N1 >) const
template<int N0, int N1, int N2>
_bz_ArrayExpr
< ArrayIndexMapping
< FastArrayIterator< T_numtype,
N_rank >, N0, N1, N2 > > operator() (IndexPlaceholder< N0 >, IndexPlaceholder< N1 >, IndexPlaceholder< N2 >) const
template<int N0, int N1, int N2, int N3>
_bz_ArrayExpr
< ArrayIndexMapping
< FastArrayIterator< T_numtype,
N_rank >, N0, N1, N2, N3 > > operator() (IndexPlaceholder< N0 >, IndexPlaceholder< N1 >, IndexPlaceholder< N2 >, IndexPlaceholder< N3 >) const
template<int N0, int N1, int N2, int N3, int N4>
_bz_ArrayExpr
< ArrayIndexMapping
< FastArrayIterator< T_numtype,
N_rank >, N0, N1, N2, N3, N4 > > operator() (IndexPlaceholder< N0 >, IndexPlaceholder< N1 >, IndexPlaceholder< N2 >, IndexPlaceholder< N3 >, IndexPlaceholder< N4 >) const
template<int N0, int N1, int N2, int N3, int N4, int N5>
_bz_ArrayExpr
< ArrayIndexMapping
< FastArrayIterator< T_numtype,
N_rank >, N0, N1, N2, N3, N4,
N5 > > operator() (IndexPlaceholder< N0 >, IndexPlaceholder< N1 >, IndexPlaceholder< N2 >, IndexPlaceholder< N3 >, IndexPlaceholder< N4 >, IndexPlaceholder< N5 >) const
template<int N0, int N1, int N2, int N3, int N4, int N5, int N6>
_bz_ArrayExpr
< ArrayIndexMapping
< FastArrayIterator< T_numtype,
N_rank >, N0, N1, N2, N3, N4,
N5, N6 > > operator() (IndexPlaceholder< N0 >, IndexPlaceholder< N1 >, IndexPlaceholder< N2 >, IndexPlaceholder< N3 >, IndexPlaceholder< N4 >, IndexPlaceholder< N5 >, IndexPlaceholder< N6 >) const
template<int N0, int N1, int N2, int N3, int N4, int N5, int N6, int N7>
_bz_ArrayExpr
< ArrayIndexMapping
< FastArrayIterator< T_numtype,
N_rank >, N0, N1, N2, N3, N4,
N5, N6, N7 > > operator() (IndexPlaceholder< N0 >, IndexPlaceholder< N1 >, IndexPlaceholder< N2 >, IndexPlaceholder< N3 >, IndexPlaceholder< N4 >, IndexPlaceholder< N5 >, IndexPlaceholder< N6 >, IndexPlaceholder< N7 >) const
template<int N0, int N1, int N2, int N3, int N4, int N5, int N6, int N7, int N8>
_bz_ArrayExpr
< ArrayIndexMapping
< FastArrayIterator< T_numtype,
N_rank >, N0, N1, N2, N3, N4,
N5, N6, N7, N8 > > operator() (IndexPlaceholder< N0 >, IndexPlaceholder< N1 >, IndexPlaceholder< N2 >, IndexPlaceholder< N3 >, IndexPlaceholder< N4 >, IndexPlaceholder< N5 >, IndexPlaceholder< N6 >, IndexPlaceholder< N7 >, IndexPlaceholder< N8 >) const
template<int N0, int N1, int N2, int N3, int N4, int N5, int N6, int N7, int N8, int N9>
_bz_ArrayExpr
< ArrayIndexMapping
< FastArrayIterator< T_numtype,
N_rank >, N0, N1, N2, N3, N4,
N5, N6, N7, N8, N9 > > operator() (IndexPlaceholder< N0 >, IndexPlaceholder< N1 >, IndexPlaceholder< N2 >, IndexPlaceholder< N3 >, IndexPlaceholder< N4 >, IndexPlaceholder< N5 >, IndexPlaceholder< N6 >, IndexPlaceholder< N7 >, IndexPlaceholder< N8 >, IndexPlaceholder< N9 >) const
template<int N0, int N1, int N2, int N3, int N4, int N5, int N6, int N7, int N8, int N9, int N10>
_bz_ArrayExpr
< ArrayIndexMapping
< FastArrayIterator< T_numtype,
N_rank >, N0, N1, N2, N3, N4,
N5, N6, N7, N8, N9, N10 > > operator() (IndexPlaceholder< N0 >, IndexPlaceholder< N1 >, IndexPlaceholder< N2 >, IndexPlaceholder< N3 >, IndexPlaceholder< N4 >, IndexPlaceholder< N5 >, IndexPlaceholder< N6 >, IndexPlaceholder< N7 >, IndexPlaceholder< N8 >, IndexPlaceholder< N9 >, IndexPlaceholder< N10 >) const
Array< typename
multicomponent_traits
< T_numtype >::T_element,
N_rank > operator[] (const unsigned component)
const Array< typename
multicomponent_traits
< T_numtype >::T_element,
N_rank > operator[] (const unsigned component) const
Array< typename
multicomponent_traits
< T_numtype >::T_element,
N_rank > operator[] (const int component)
const Array< typename
multicomponent_traits
< T_numtype >::T_element,
N_rank > operator[] (const int component) const
template<typename T_indexContainer >
IndirectArray< T_array,
T_indexContainer > operator[] (const T_indexContainer &index)
ListInitializationSwitch
< T_array, T_numtype * > operator= (T_numtype x)
T_array & initialize (T_numtype)
T_array & operator+= (T_numtype)
T_array & operator-= (T_numtype)
T_array & operator*= (T_numtype)
T_array & operator/= (T_numtype)
T_array & operator%= (T_numtype)
T_array & operator^= (T_numtype)
T_array & operator&= (T_numtype)
T_array & operator|= (T_numtype)
T_array & operator>>= (T_numtype)
T_array & operator<<= (T_numtype)
T_array & operator= (const Array< T_numtype, N_rank > &)
template<typename P_numtype2 >
T_array & operator= (const Array< P_numtype2, N_rank > &)
template<typename P_numtype2 >
T_array & operator+= (const Array< P_numtype2, N_rank > &)
template<typename P_numtype2 >
T_array & operator-= (const Array< P_numtype2, N_rank > &)
template<typename P_numtype2 >
T_array & operator*= (const Array< P_numtype2, N_rank > &)
template<typename P_numtype2 >
T_array & operator/= (const Array< P_numtype2, N_rank > &)
template<typename P_numtype2 >
T_array & operator%= (const Array< P_numtype2, N_rank > &)
template<typename P_numtype2 >
T_array & operator^= (const Array< P_numtype2, N_rank > &)
template<typename P_numtype2 >
T_array & operator&= (const Array< P_numtype2, N_rank > &)
template<typename P_numtype2 >
T_array & operator|= (const Array< P_numtype2, N_rank > &)
template<typename P_numtype2 >
T_array & operator>>= (const Array< P_numtype2, N_rank > &)
template<typename P_numtype2 >
T_array & operator<<= (const Array< P_numtype2, N_rank > &)
template<typename T_expr >
T_array & operator= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr)
template<typename T_expr >
T_array & operator+= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr)
template<typename T_expr >
T_array & operator-= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr)
template<typename T_expr >
T_array & operator*= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr)
template<typename T_expr >
T_array & operator/= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr)
template<typename T_expr >
T_array & operator%= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr)
template<typename T_expr >
T_array & operator^= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr)
template<typename T_expr >
T_array & operator&= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr)
template<typename T_expr >
T_array & operator|= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr)
template<typename T_expr >
T_array & operator>>= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr)
template<typename T_expr >
T_array & operator<<= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr)
template<typename T_expr , typename T_update >
T_array & evaluate (T_expr expr, T_update)
template<typename T_expr , typename T_update >
T_array & evaluateWithIndexTraversal1 (T_expr expr, T_update)
template<typename T_expr , typename T_update >
T_array & evaluateWithIndexTraversalN (T_expr expr, T_update)
template<typename T_expr , typename T_update >
T_array & evaluateWithStackTraversal1 (T_expr expr, T_update)
template<typename T_expr , typename T_update >
T_array & evaluateWithStackTraversalN (T_expr expr, T_update)
T_numtype *restrict getInitializationIterator ()
bool canCollapse (int outerRank, int innerRank) const
Static Public Attributes
static const int _bz_rank = N_rank
Protected Member Functions
_bz_inline2 void computeStrides ()
_bz_inline2 void setupStorage (int rank)
void constructSubarray (Array< T_numtype, N_rank > &array, const RectDomain< N_rank > &)
void constructSubarray (Array< T_numtype, N_rank > &array, const StridedDomain< N_rank > &)
void constructSubarray (Array< T_numtype, N_rank > &array, Range r0)
void constructSubarray (Array< T_numtype, N_rank > &array, Range r0, Range r1)
void constructSubarray (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2)
void constructSubarray (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3)
void constructSubarray (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4)
void constructSubarray (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5)
void constructSubarray (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6)
void constructSubarray (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7)
void constructSubarray (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8)
void constructSubarray (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9)
void constructSubarray (Array< T_numtype, N_rank > &array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10)
void calculateZeroOffset ()
template<int N_rank2, typename R0 , typename R1 , typename R2 , typename R3 , typename R4 , typename R5 , typename R6 , typename R7 , typename R8 , typename R9 , typename R10 >
void constructSlice (Array< T_numtype, N_rank2 > &array, R0 r0, R1 r1, R2 r2, R3 r3, R4 r4, R5 r5, R6 r6, R7 r7, R8 r8, R9 r9, R10 r10)
template<int N_rank2>
void slice (int &setRank, Range r, Array< T_numtype, N_rank2 > &array, TinyVector< int, N_rank2 > &rankMap, int sourceRank)
template<int N_rank2>
void slice (int &setRank, int i, Array< T_numtype, N_rank2 > &array, TinyVector< int, N_rank2 > &rankMap, int sourceRank)
template<int N_rank2>
void slice (int &, nilArraySection, Array< T_numtype, N_rank2 > &, TinyVector< int, N_rank2 > &, int)
void doTranspose (int destRank, int sourceRank, T_array &array)
Protected Attributes
GeneralArrayStorage< N_rank > storage_
TinyVector< int, N_rank > length_
TinyVector< diffType, N_rank > stride_
diffType zeroOffset_
Private Types
typedef MemoryBlockReference
< P_numtype > T_base
template<typename P_numtype, int N_rank>
class Array< P_numtype, N_rank >
Member Typedef Documentation
template<typename P_numtype, int N_rank> typedef ConstArrayIterator<T_numtype,N_rank> Array< P_numtype, N_rank >::const_iterator
template<typename P_numtype, int N_rank> typedef ArrayIterator<T_numtype,N_rank> Array< P_numtype, N_rank >::iterator
template<typename P_numtype, int N_rank> typedef Array<T_numtype, N_rank> Array< P_numtype, N_rank >::T_array
template<typename P_numtype, int N_rank> typedef MemoryBlockReference<P_numtype> Array< P_numtype, N_rank >::T_base [private]
template<typename P_numtype, int N_rank> typedef TinyVector<int, N_rank> Array< P_numtype, N_rank >::T_index
template<typename P_numtype, int N_rank> typedef FastArrayIterator<T_numtype, N_rank> Array< P_numtype, N_rank >::T_iterator
template<typename P_numtype, int N_rank> typedef P_numtype Array< P_numtype, N_rank >::T_numtype
Constructor & Destructor Documentation
template<typename P_numtype, int N_rank> template<typename T_expr > Array< P_numtype, N_rank >::Array (_bz_ArrayExpr< T_expr > expr) [inline, explicit]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (int length0, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline, explicit]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (int length0, int length1, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (int length0, int length1, int length2, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (int length0, int length1, int length2, int length3, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (int length0, int length1, int length2, int length3, int length4, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (int length0, int length1, int length2, int length3, int length4, int length5, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (int length0, int length1, int length2, int length3, int length4, int length5, int length6, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (int length0, int length1, int length2, int length3, int length4, int length5, int length6, int length7, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (int length0, int length1, int length2, int length3, int length4, int length5, int length6, int length7, int length8, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (int length0, int length1, int length2, int length3, int length4, int length5, int length6, int length7, int length8, int length9, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (int length0, int length1, int length2, int length3, int length4, int length5, int length6, int length7, int length8, int length9, int length10, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (T_numtype *restrict dataFirst, TinyVector< int, N_rank > shape, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (T_numtype *restrict dataFirst, TinyVector< int, N_rank > shape, TinyVector< diffType, N_rank > stride, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (T_numtype *restrict dataFirst, TinyVector< int, N_rank > shape, preexistingMemoryPolicy deletionPolicy, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References duplicateData.
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (T_numtype *restrict dataFirst, TinyVector< int, N_rank > shape, TinyVector< diffType, N_rank > stride, preexistingMemoryPolicy deletionPolicy, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References duplicateData.
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (const TinyVector< int, N_rank > & extent, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (const TinyVector< int, N_rank > & lbounds, const TinyVector< int, N_rank > & extent, const GeneralArrayStorage< N_rank > & storage = GeneralArrayStorage< N_rank >())
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Range r0, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References Range::first(), Range::isAscendingContiguous(), and Range::length().
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Range r0, Range r1, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References Range::first(), Range::isAscendingContiguous(), and Range::length().
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Range r0, Range r1, Range r2, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References Range::first(), Range::isAscendingContiguous(), and Range::length().
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Range r0, Range r1, Range r2, Range r3, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References Range::first(), Range::isAscendingContiguous(), and Range::length().
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Range r0, Range r1, Range r2, Range r3, Range r4, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References Range::first(), Range::isAscendingContiguous(), and Range::length().
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References Range::first(), Range::isAscendingContiguous(), and Range::length().
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References Range::first(), Range::isAscendingContiguous(), and Range::length().
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References Range::first(), Range::isAscendingContiguous(), and Range::length().
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References Range::first(), Range::isAscendingContiguous(), and Range::length().
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References Range::first(), Range::isAscendingContiguous(), and Range::length().
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10, GeneralArrayStorage< N_rank > storage = GeneralArrayStorage<N_rank>()) [inline]
References Range::first(), Range::isAscendingContiguous(), and Range::length().
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (const Array< T_numtype, N_rank > & array) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (const TinyVector< int, N_rank-1 > & shape, int lastExtent, const GeneralArrayStorage< N_rank > & storage)
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, Range r0) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, Range r0, Range r1) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, const RectDomain< N_rank > & subdomain) [inline]
template<typename P_numtype, int N_rank> Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank > & array, const StridedDomain< N_rank > & subdomain) [inline]
template<typename P_numtype, int N_rank> template<int N_rank2, typename R0 , typename R1 , typename R2 , typename R3 , typename R4 , typename R5 , typename R6 , typename R7 , typename R8 , typename R9 , typename R10 > Array< P_numtype, N_rank >::Array (Array< T_numtype, N_rank2 > & array, R0 r0, R1 r1, R2 r2, R3 r3, R4 r4, R5 r5, R6 r6, R7 r7, R8 r8, R9 r9, R10 r10) [inline]
Member Function Documentation
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (int BZ_DEBUG_PARAMi0, int BZ_DEBUG_PARAMi1, int BZ_DEBUG_PARAMi2, int BZ_DEBUG_PARAMi3, int BZ_DEBUG_PARAMi4, int BZ_DEBUG_PARAMi5, int BZ_DEBUG_PARAMi6, int BZ_DEBUG_PARAMi7, int BZ_DEBUG_PARAMi8, int BZ_DEBUG_PARAMi9, int BZ_DEBUG_PARAMi10) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (int BZ_DEBUG_PARAMi0, int BZ_DEBUG_PARAMi1, int BZ_DEBUG_PARAMi2, int BZ_DEBUG_PARAMi3, int BZ_DEBUG_PARAMi4, int BZ_DEBUG_PARAMi5, int BZ_DEBUG_PARAMi6, int BZ_DEBUG_PARAMi7, int BZ_DEBUG_PARAMi8, int BZ_DEBUG_PARAMi9) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (int BZ_DEBUG_PARAMi0, int BZ_DEBUG_PARAMi1, int BZ_DEBUG_PARAMi2, int BZ_DEBUG_PARAMi3, int BZ_DEBUG_PARAMi4, int BZ_DEBUG_PARAMi5, int BZ_DEBUG_PARAMi6, int BZ_DEBUG_PARAMi7, int BZ_DEBUG_PARAMi8) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (int BZ_DEBUG_PARAMi0, int BZ_DEBUG_PARAMi1, int BZ_DEBUG_PARAMi2, int BZ_DEBUG_PARAMi3, int BZ_DEBUG_PARAMi4, int BZ_DEBUG_PARAMi5, int BZ_DEBUG_PARAMi6, int BZ_DEBUG_PARAMi7) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (int BZ_DEBUG_PARAMi0, int BZ_DEBUG_PARAMi1, int BZ_DEBUG_PARAMi2, int BZ_DEBUG_PARAMi3, int BZ_DEBUG_PARAMi4, int BZ_DEBUG_PARAMi5, int BZ_DEBUG_PARAMi6) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (int BZ_DEBUG_PARAMi0, int BZ_DEBUG_PARAMi1, int BZ_DEBUG_PARAMi2, int BZ_DEBUG_PARAMi3, int BZ_DEBUG_PARAMi4, int BZ_DEBUG_PARAMi5) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (int BZ_DEBUG_PARAMi0, int BZ_DEBUG_PARAMi1, int BZ_DEBUG_PARAMi2, int BZ_DEBUG_PARAMi3, int BZ_DEBUG_PARAMi4) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (int BZ_DEBUG_PARAMi0, int BZ_DEBUG_PARAMi1, int BZ_DEBUG_PARAMi2, int BZ_DEBUG_PARAMi3) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (int BZ_DEBUG_PARAMi0, int BZ_DEBUG_PARAMi1, int BZ_DEBUG_PARAMi2) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (int BZ_DEBUG_PARAMi0, int BZ_DEBUG_PARAMi1) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (int BZ_DEBUG_PARAMi0) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::assertInRange (const T_index & BZ_DEBUG_PARAMindex) const [inline]
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::base (int rank) const [inline]
template<typename P_numtype, int N_rank> const TinyVector<int, N_rank>& Array< P_numtype, N_rank >::base () const [inline]
template<typename P_numtype, int N_rank> const_iterator Array< P_numtype, N_rank >::begin () const [inline]
template<typename P_numtype, int N_rank> iterator Array< P_numtype, N_rank >::begin () [inline]
Referenced by find().
template<typename P_numtype, int N_rank> T_iterator Array< P_numtype, N_rank >::beginFast () const [inline]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::calculateZeroOffset () [protected]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::canCollapse (int outerRank, int innerRank) const [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > Array<P_numtype2,N_rank> Array< P_numtype, N_rank >::chopComponent (P_numtype2 a, int compNum, int numComponents) const [inline]
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::cols () const [inline]
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::columns () const [inline]
template<typename P_numtype, int N_rank> _bz_inline2 void Array< P_numtype, N_rank >::computeStrides () [protected]
template<typename P_numtype, int N_rank> template<int N_rank2, typename R0 , typename R1 , typename R2 , typename R3 , typename R4 , typename R5 , typename R6 , typename R7 , typename R8 , typename R9 , typename R10 > void Array< P_numtype, N_rank >::constructSlice (Array< T_numtype, N_rank2 > & array, R0 r0, R1 r1, R2 r2, R3 r3, R4 r4, R5 r5, R6 r6, R7 r7, R8 r8, R9 r9, R10 r10) [inline, protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4, Range r5) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3, Range r4) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2, Range r3) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, Range r0, Range r1, Range r2) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, Range r0, Range r1) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, Range r0) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, const StridedDomain< N_rank > &) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::constructSubarray (Array< T_numtype, N_rank > & array, const RectDomain< N_rank > &) [protected]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::copy () const
template<typename P_numtype, int N_rank> T_numtype* restrict Array< P_numtype, N_rank >::data () [inline]
template<typename P_numtype, int N_rank> const T_numtype* restrict Array< P_numtype, N_rank >::data () const [inline]
template<typename P_numtype, int N_rank> T_numtype* restrict Array< P_numtype, N_rank >::dataFirst () [inline]
template<typename P_numtype, int N_rank> const T_numtype* restrict Array< P_numtype, N_rank >::dataFirst () const [inline]
template<typename P_numtype, int N_rank> diffType Array< P_numtype, N_rank >::dataFirstOffset () const [inline]
References i.
template<typename P_numtype, int N_rank> diffType Array< P_numtype, N_rank >::dataOffset () const [inline]
template<typename P_numtype, int N_rank> T_numtype* restrict Array< P_numtype, N_rank >::dataZero () [inline]
template<typename P_numtype, int N_rank> const T_numtype* restrict Array< P_numtype, N_rank >::dataZero () const [inline]
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::depth () const [inline]
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::dimensions () const [inline]
template<typename P_numtype, int N_rank> RectDomain<N_rank> Array< P_numtype, N_rank >::domain () const [inline]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::doTranspose (int destRank, int sourceRank, T_array & array) [protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::dumpStructureInformation (ostream & os = cout) const
template<typename P_numtype, int N_rank> const_iterator Array< P_numtype, N_rank >::end () const [inline]
template<typename P_numtype, int N_rank> iterator Array< P_numtype, N_rank >::end () [inline]
Referenced by find().
template<typename P_numtype, int N_rank> template<typename T_expr , typename T_update > T_array& Array< P_numtype, N_rank >::evaluate (T_expr expr, T_update) [inline]
template<typename P_numtype, int N_rank> template<typename T_expr , typename T_update > T_array& Array< P_numtype, N_rank >::evaluateWithIndexTraversal1 (T_expr expr, T_update) [inline]
template<typename P_numtype, int N_rank> template<typename T_expr , typename T_update > T_array& Array< P_numtype, N_rank >::evaluateWithIndexTraversalN (T_expr expr, T_update) [inline]
template<typename P_numtype, int N_rank> template<typename T_expr , typename T_update > T_array& Array< P_numtype, N_rank >::evaluateWithStackTraversal1 (T_expr expr, T_update) [inline]
template<typename P_numtype, int N_rank> template<typename T_expr , typename T_update > T_array& Array< P_numtype, N_rank >::evaluateWithStackTraversalN (T_expr expr, T_update) [inline]
template<typename P_numtype, int N_rank> const TinyVector<int,N_rank>& Array< P_numtype, N_rank >::extent () const [inline]
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::extent (int rank) const [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > Array<P_numtype2,N_rank> Array< P_numtype, N_rank >::extractComponent (P_numtype2 , int compNum, int numComponents) const [inline]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::free () [inline]
template<typename P_numtype, int N_rank> T_numtype* restrict Array< P_numtype, N_rank >::getInitializationIterator () [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::initialize (T_numtype)
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (const T_index & index) const [inline]
References i.
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (int i0, int i1, int i2, int i3, int i4, int i5, int i6) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (int i0, int i1, int i2, int i3, int i4, int i5) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (int i0, int i1, int i2, int i3, int i4) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (int i0, int i1, int i2, int i3) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (int i0, int i1, int i2) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (int i0, int i1) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRange (int i0) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isInRangeForDim (int i, int d) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isMajorRank (int rank) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isMinorRank (int rank) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isRankStoredAscending (int rank) const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::isStorageContiguous () const
template<typename P_numtype, int N_rank> TinyVector<int,N_rank> Array< P_numtype, N_rank >::lbound () const [inline]
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::lbound (int rank) const [inline]
template<typename P_numtype, int N_rank> const TinyVector<int, N_rank>& Array< P_numtype, N_rank >::length () const [inline]
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::length (int rank) const [inline]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::makeUnique ()
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::noConst () const [inline]
template<typename P_numtype, int N_rank> sizeType Array< P_numtype, N_rank >::numElements () const [inline]
template<typename P_numtype, int N_rank> template<typename T_expr > T_array& Array< P_numtype, N_rank >::operator%= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr) [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > T_array& Array< P_numtype, N_rank >::operator%= (const Array< P_numtype2, N_rank > &) [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::operator%= (T_numtype)
template<typename P_numtype, int N_rank> template<typename T_expr > T_array& Array< P_numtype, N_rank >::operator&= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr) [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > T_array& Array< P_numtype, N_rank >::operator&= (const Array< P_numtype2, N_rank > &) [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::operator&= (T_numtype)
template<typename P_numtype, int N_rank> template<int N0, int N1, int N2, int N3, int N4, int N5, int N6, int N7, int N8, int N9, int N10> _bz_ArrayExpr<ArrayIndexMapping<FastArrayIterator<T_numtype, N_rank>, N0, N1, N2, N3, N4, N5, N6, N7, N8, N9, N10> > Array< P_numtype, N_rank >::operator() (IndexPlaceholder< N0 > , IndexPlaceholder< N1 > , IndexPlaceholder< N2 > , IndexPlaceholder< N3 > , IndexPlaceholder< N4 > , IndexPlaceholder< N5 > , IndexPlaceholder< N6 > , IndexPlaceholder< N7 > , IndexPlaceholder< N8 > , IndexPlaceholder< N9 > , IndexPlaceholder< N10 >) const [inline]
template<typename P_numtype, int N_rank> template<int N0, int N1, int N2, int N3, int N4, int N5, int N6, int N7, int N8, int N9> _bz_ArrayExpr<ArrayIndexMapping<FastArrayIterator<T_numtype, N_rank>, N0, N1, N2, N3, N4, N5, N6, N7, N8, N9> > Array< P_numtype, N_rank >::operator() (IndexPlaceholder< N0 > , IndexPlaceholder< N1 > , IndexPlaceholder< N2 > , IndexPlaceholder< N3 > , IndexPlaceholder< N4 > , IndexPlaceholder< N5 > , IndexPlaceholder< N6 > , IndexPlaceholder< N7 > , IndexPlaceholder< N8 > , IndexPlaceholder< N9 >) const [inline]
template<typename P_numtype, int N_rank> template<int N0, int N1, int N2, int N3, int N4, int N5, int N6, int N7, int N8> _bz_ArrayExpr<ArrayIndexMapping<FastArrayIterator<T_numtype, N_rank>, N0, N1, N2, N3, N4, N5, N6, N7, N8> > Array< P_numtype, N_rank >::operator() (IndexPlaceholder< N0 > , IndexPlaceholder< N1 > , IndexPlaceholder< N2 > , IndexPlaceholder< N3 > , IndexPlaceholder< N4 > , IndexPlaceholder< N5 > , IndexPlaceholder< N6 > , IndexPlaceholder< N7 > , IndexPlaceholder< N8 >) const [inline]
template<typename P_numtype, int N_rank> template<int N0, int N1, int N2, int N3, int N4, int N5, int N6, int N7> _bz_ArrayExpr<ArrayIndexMapping<FastArrayIterator<T_numtype, N_rank>, N0, N1, N2, N3, N4, N5, N6, N7> > Array< P_numtype, N_rank >::operator() (IndexPlaceholder< N0 > , IndexPlaceholder< N1 > , IndexPlaceholder< N2 > , IndexPlaceholder< N3 > , IndexPlaceholder< N4 > , IndexPlaceholder< N5 > , IndexPlaceholder< N6 > , IndexPlaceholder< N7 >) const [inline]
template<typename P_numtype, int N_rank> template<int N0, int N1, int N2, int N3, int N4, int N5, int N6> _bz_ArrayExpr<ArrayIndexMapping<FastArrayIterator<T_numtype, N_rank>, N0, N1, N2, N3, N4, N5, N6> > Array< P_numtype, N_rank >::operator() (IndexPlaceholder< N0 > , IndexPlaceholder< N1 > , IndexPlaceholder< N2 > , IndexPlaceholder< N3 > , IndexPlaceholder< N4 > , IndexPlaceholder< N5 > , IndexPlaceholder< N6 >) const [inline]
template<typename P_numtype, int N_rank> template<int N0, int N1, int N2, int N3, int N4, int N5> _bz_ArrayExpr<ArrayIndexMapping<FastArrayIterator<T_numtype, N_rank>, N0, N1, N2, N3, N4, N5> > Array< P_numtype, N_rank >::operator() (IndexPlaceholder< N0 > , IndexPlaceholder< N1 > , IndexPlaceholder< N2 > , IndexPlaceholder< N3 > , IndexPlaceholder< N4 > , IndexPlaceholder< N5 >) const [inline]
template<typename P_numtype, int N_rank> template<int N0, int N1, int N2, int N3, int N4> _bz_ArrayExpr<ArrayIndexMapping<FastArrayIterator<T_numtype, N_rank>, N0, N1, N2, N3, N4> > Array< P_numtype, N_rank >::operator() (IndexPlaceholder< N0 > , IndexPlaceholder< N1 > , IndexPlaceholder< N2 > , IndexPlaceholder< N3 > , IndexPlaceholder< N4 >) const [inline]
template<typename P_numtype, int N_rank> template<int N0, int N1, int N2, int N3> _bz_ArrayExpr<ArrayIndexMapping<FastArrayIterator<T_numtype, N_rank>, N0, N1, N2, N3> > Array< P_numtype, N_rank >::operator() (IndexPlaceholder< N0 > , IndexPlaceholder< N1 > , IndexPlaceholder< N2 > , IndexPlaceholder< N3 >) const [inline]
template<typename P_numtype, int N_rank> template<int N0, int N1, int N2> _bz_ArrayExpr<ArrayIndexMapping<FastArrayIterator<T_numtype, N_rank>, N0, N1, N2> > Array< P_numtype, N_rank >::operator() (IndexPlaceholder< N0 > , IndexPlaceholder< N1 > , IndexPlaceholder< N2 >) const [inline]
template<typename P_numtype, int N_rank> template<int N0, int N1> _bz_ArrayExpr<ArrayIndexMapping<FastArrayIterator<T_numtype, N_rank>, N0, N1> > Array< P_numtype, N_rank >::operator() (IndexPlaceholder< N0 > , IndexPlaceholder< N1 >) const [inline]
template<typename P_numtype, int N_rank> template<int N0> _bz_ArrayExpr<ArrayIndexMapping<FastArrayIterator<T_numtype, N_rank>, N0> > Array< P_numtype, N_rank >::operator() (IndexPlaceholder< N0 >) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5, Range r6) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (Range r0, Range r1, Range r2, Range r3, Range r4, Range r5) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (Range r0, Range r1, Range r2, Range r3, Range r4) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (Range r0, Range r1, Range r2, Range r3) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (Range r0, Range r1, Range r2) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (Range r0, Range r1) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (Range r0) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (const StridedDomain< N_rank > & subdomain) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::operator() (const RectDomain< N_rank > & subdomain) const [inline]
template<typename P_numtype, int N_rank> T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10) const [inline]
template<typename P_numtype, int N_rank> T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9) const [inline]
template<typename P_numtype, int N_rank> T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8) const [inline]
template<typename P_numtype, int N_rank> T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7) const [inline]
template<typename P_numtype, int N_rank> T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5, int i6) const [inline]
template<typename P_numtype, int N_rank> T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4, int i5) const [inline]
template<typename P_numtype, int N_rank> T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3, int i4) const [inline]
template<typename P_numtype, int N_rank> T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2, int i3) const [inline]
template<typename P_numtype, int N_rank> T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1, int i2) const [inline]
template<typename P_numtype, int N_rank> T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0, int i1) const [inline]
template<typename P_numtype, int N_rank> T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (int i0) const [inline]
template<typename P_numtype, int N_rank> T_numtype& Array< P_numtype, N_rank >::operator() (const TinyVector< int, 11 > & index) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (const TinyVector< int, 11 > & index) const [inline]
template<typename P_numtype, int N_rank> T_numtype& Array< P_numtype, N_rank >::operator() (const TinyVector< int, 10 > & index) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (const TinyVector< int, 10 > & index) const [inline]
template<typename P_numtype, int N_rank> T_numtype& Array< P_numtype, N_rank >::operator() (const TinyVector< int, 9 > & index) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (const TinyVector< int, 9 > & index) const [inline]
template<typename P_numtype, int N_rank> T_numtype& Array< P_numtype, N_rank >::operator() (const TinyVector< int, 8 > & index) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (const TinyVector< int, 8 > & index) const [inline]
template<typename P_numtype, int N_rank> T_numtype& Array< P_numtype, N_rank >::operator() (const TinyVector< int, 7 > & index) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (const TinyVector< int, 7 > & index) const [inline]
template<typename P_numtype, int N_rank> T_numtype& Array< P_numtype, N_rank >::operator() (const TinyVector< int, 6 > & index) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (const TinyVector< int, 6 > & index) const [inline]
template<typename P_numtype, int N_rank> T_numtype& Array< P_numtype, N_rank >::operator() (const TinyVector< int, 5 > & index) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (const TinyVector< int, 5 > & index) const [inline]
template<typename P_numtype, int N_rank> T_numtype& Array< P_numtype, N_rank >::operator() (const TinyVector< int, 4 > & index) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (const TinyVector< int, 4 > & index) const [inline]
template<typename P_numtype, int N_rank> T_numtype& Array< P_numtype, N_rank >::operator() (TinyVector< int, 3 > index) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (TinyVector< int, 3 > index) const [inline]
template<typename P_numtype, int N_rank> T_numtype& Array< P_numtype, N_rank >::operator() (TinyVector< int, 2 > index) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (TinyVector< int, 2 > index) const [inline]
template<typename P_numtype, int N_rank> T_numtype& Array< P_numtype, N_rank >::operator() (TinyVector< int, 1 > index) [inline]
template<typename P_numtype, int N_rank> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (TinyVector< int, 1 > index) const [inline]
template<typename P_numtype, int N_rank> template<int N_rank2> T_numtype& restrict Array< P_numtype, N_rank >::operator() (const TinyVector< int, N_rank2 > & index) [inline]
template<typename P_numtype, int N_rank> template<int N_rank2> const T_numtype& restrict Array< P_numtype, N_rank >::operator() (const TinyVector< int, N_rank2 > & index) const [inline]
template<typename P_numtype, int N_rank> template<typename T_expr > T_array& Array< P_numtype, N_rank >::operator*= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr) [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > T_array& Array< P_numtype, N_rank >::operator*= (const Array< P_numtype2, N_rank > &) [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::operator*= (T_numtype)
template<typename P_numtype, int N_rank> template<typename T_expr > T_array& Array< P_numtype, N_rank >::operator+= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr) [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > T_array& Array< P_numtype, N_rank >::operator+= (const Array< P_numtype2, N_rank > &) [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::operator+= (T_numtype)
template<typename P_numtype, int N_rank> template<typename T_expr > T_array& Array< P_numtype, N_rank >::operator-= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr) [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > T_array& Array< P_numtype, N_rank >::operator-= (const Array< P_numtype2, N_rank > &) [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::operator-= (T_numtype)
template<typename P_numtype, int N_rank> template<typename T_expr > T_array& Array< P_numtype, N_rank >::operator/= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr) [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > T_array& Array< P_numtype, N_rank >::operator/= (const Array< P_numtype2, N_rank > &) [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::operator/= (T_numtype)
template<typename P_numtype, int N_rank> template<typename T_expr > T_array& Array< P_numtype, N_rank >::operator<<= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr) [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > T_array& Array< P_numtype, N_rank >::operator<<= (const Array< P_numtype2, N_rank > &) [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::operator<<= (T_numtype)
template<typename P_numtype, int N_rank> template<typename T_expr > T_array& Array< P_numtype, N_rank >::operator= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr) [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > T_array& Array< P_numtype, N_rank >::operator= (const Array< P_numtype2, N_rank > &) [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::operator= (const Array< T_numtype, N_rank > &)
template<typename P_numtype, int N_rank> ListInitializationSwitch<T_array,T_numtype*> Array< P_numtype, N_rank >::operator= (T_numtype x) [inline]
template<typename P_numtype, int N_rank> template<typename T_expr > T_array& Array< P_numtype, N_rank >::operator>>= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr) [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > T_array& Array< P_numtype, N_rank >::operator>>= (const Array< P_numtype2, N_rank > &) [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::operator>>= (T_numtype)
template<typename P_numtype, int N_rank> template<typename T_indexContainer > IndirectArray<T_array, T_indexContainer> Array< P_numtype, N_rank >::operator[] (const T_indexContainer & index) [inline]
template<typename P_numtype, int N_rank> const Array<typename multicomponent_traits<T_numtype>::T_element,N_rank> Array< P_numtype, N_rank >::operator[] (const int component) const [inline]
template<typename P_numtype, int N_rank> Array<typename multicomponent_traits<T_numtype>::T_element,N_rank> Array< P_numtype, N_rank >::operator[] (const int component) [inline]
template<typename P_numtype, int N_rank> const Array<typename multicomponent_traits<T_numtype>::T_element,N_rank> Array< P_numtype, N_rank >::operator[] (const unsigned component) const [inline]
template<typename P_numtype, int N_rank> Array<typename multicomponent_traits<T_numtype>::T_element,N_rank> Array< P_numtype, N_rank >::operator[] (const unsigned component) [inline]
template<typename P_numtype, int N_rank> template<typename T_expr > T_array& Array< P_numtype, N_rank >::operator^= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr) [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > T_array& Array< P_numtype, N_rank >::operator^= (const Array< P_numtype2, N_rank > &) [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::operator^= (T_numtype)
template<typename P_numtype, int N_rank> template<typename T_expr > T_array& Array< P_numtype, N_rank >::operator|= (BZ_ETPARM(_bz_ArrayExpr< T_expr >) expr) [inline]
template<typename P_numtype, int N_rank> template<typename P_numtype2 > T_array& Array< P_numtype, N_rank >::operator|= (const Array< P_numtype2, N_rank > &) [inline]
template<typename P_numtype, int N_rank> T_array& Array< P_numtype, N_rank >::operator|= (T_numtype)
template<typename P_numtype, int N_rank> const TinyVector<int, N_rank>& Array< P_numtype, N_rank >::ordering () const [inline]
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::ordering (int storageRankIndex) const [inline]
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::rank () const [inline]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::reference (const T_array &)
Referenced by swap().
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::reindex (const TinyVector< int, N_rank > &)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::reindexSelf (const TinyVector< int, N_rank > &)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (const TinyVector< int, N_rank > &)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10, Range r11)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9, Range r10)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8, Range r9)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7, Range r8)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6, Range r7)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (Range r1, Range r2, Range r3, Range r4, Range r5, Range r6)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (Range r1, Range r2, Range r3, Range r4, Range r5)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (Range r1, Range r2, Range r3, Range r4)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (Range r1, Range r2, Range r3)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (Range r1, Range r2)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (Range r1)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9, int extent10, int extent11)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9, int extent10)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (int extent1, int extent2, int extent3, int extent4, int extent5)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (int extent1, int extent2, int extent3, int extent4)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (int extent1, int extent2, int extent3)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (int extent1, int extent2)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resize (int extent)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9, int extent10, int extent11)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9, int extent10)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8, int extent9)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7, int extent8)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6, int extent7)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5, int extent6)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (int extent1, int extent2, int extent3, int extent4, int extent5)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (int extent1, int extent2, int extent3, int extent4)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (int extent1, int extent2, int extent3)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (int extent1, int extent2)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (int extent)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::resizeAndPreserve (const TinyVector< int, N_rank > &)
Referenced by find().
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::reverse (int rank)
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::reverseSelf (int rank)
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::rows () const [inline]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::setStorage (GeneralArrayStorage< N_rank >)
template<typename P_numtype, int N_rank> _bz_inline2 void Array< P_numtype, N_rank >::setupStorage (int rank) [protected]
template<typename P_numtype, int N_rank> const TinyVector<int, N_rank>& Array< P_numtype, N_rank >::shape () const [inline]
template<typename P_numtype, int N_rank> sizeType Array< P_numtype, N_rank >::size () const [inline]
Referenced by find().
template<typename P_numtype, int N_rank> template<int N_rank2> void Array< P_numtype, N_rank >::slice (int & , nilArraySection , Array< T_numtype, N_rank2 > & , TinyVector< int, N_rank2 > & , int) [inline, protected]
template<typename P_numtype, int N_rank> template<int N_rank2> void Array< P_numtype, N_rank >::slice (int & setRank, int i, Array< T_numtype, N_rank2 > & array, TinyVector< int, N_rank2 > & rankMap, int sourceRank) [inline, protected]
template<typename P_numtype, int N_rank> template<int N_rank2> void Array< P_numtype, N_rank >::slice (int & setRank, Range r, Array< T_numtype, N_rank2 > & array, TinyVector< int, N_rank2 > & rankMap, int sourceRank) [inline, protected]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::slice (int rank, Range r)
template<typename P_numtype, int N_rank> diffType Array< P_numtype, N_rank >::stride (int rank) const [inline]
template<typename P_numtype, int N_rank> const TinyVector<diffType, N_rank>& Array< P_numtype, N_rank >::stride () const [inline]
template<typename P_numtype, int N_rank> bool Array< P_numtype, N_rank >::threadLocal (bool disableLock = true) const [inline]
template<typename P_numtype, int N_rank> T_array Array< P_numtype, N_rank >::transpose (int r0, int r1, int r2 = 0, int r3 = 0, int r4 = 0, int r5 = 0, int r6 = 0, int r7 = 0, int r8 = 0, int r9 = 0, int r10 = 0) const
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::transposeSelf (int r0, int r1, int r2 = 0, int r3 = 0, int r4 = 0, int r5 = 0, int r6 = 0, int r7 = 0, int r8 = 0, int r9 = 0, int r10 = 0)
template<typename P_numtype, int N_rank> TinyVector<int, N_rank> Array< P_numtype, N_rank >::ubound () const [inline]
References i.
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::ubound (int rank) const [inline]
template<typename P_numtype, int N_rank> void Array< P_numtype, N_rank >::weakReference (const T_array &)
template<typename P_numtype, int N_rank> int Array< P_numtype, N_rank >::zeroOffset () const [inline]
Member Data Documentation
template<typename P_numtype, int N_rank> const int Array< P_numtype, N_rank >::_bz_rank = N_rank [static]
template<typename P_numtype, int N_rank> TinyVector<int, N_rank> Array< P_numtype, N_rank >::length_ [protected]
template<typename P_numtype, int N_rank> GeneralArrayStorage<N_rank> Array< P_numtype, N_rank >::storage_ [protected]
template<typename P_numtype, int N_rank> TinyVector<diffType, N_rank> Array< P_numtype, N_rank >::stride_ [protected]
template<typename P_numtype, int N_rank> diffType Array< P_numtype, N_rank >::zeroOffset_ [protected]
The documentation for this class was generated from the following file:
blitz/array-impl.h