blitz: Gamma< T, IRNG, stateTag > Class Template Reference
Gamma< T, IRNG, stateTag > Class Template Reference
#include <gamma.h>
Public Types
typedef T T_numtype
Public Member Functions
Gamma ()
Gamma (unsigned int i)
Gamma (T mean)
Gamma (T mean, unsigned int i)
T random ()
void setMean (T mean)
Protected Member Functions
T ranf ()
T snorm ()
T sexpo ()
T fsign (T num, T sign)
Protected Attributes
NormalUnit< T, IRNG, sharedState > normal_
ExponentialUnit< T, IRNG,
sharedState > exponential_
T a
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState>
class Gamma< T, IRNG, stateTag >
Member Typedef Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> typedef T Gamma< T, IRNG, stateTag >::T_numtype
Reimplemented from UniformOpen< T, IRNG, stateTag >.
Reimplemented in ChiSquare< T, IRNG, stateTag >.
Constructor & Destructor Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> Gamma< T, IRNG, stateTag >::Gamma () [inline]
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> Gamma< T, IRNG, stateTag >::Gamma (unsigned int i) [inline, explicit]
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> Gamma< T, IRNG, stateTag >::Gamma (T mean) [inline]
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> Gamma< T, IRNG, stateTag >::Gamma (T mean, unsigned int i) [inline]
Member Function Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Gamma< T, IRNG, stateTag >::fsign (T num, T sign) [inline, protected]
Referenced by Gamma< T, IRNG, stateTag >::random().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Gamma< T, IRNG, stateTag >::random ()
Reimplemented from UniformOpen< T, IRNG, stateTag >.
Reimplemented in ChiSquare< T, IRNG, stateTag >.
Referenced by ChiSquare< T, IRNG, stateTag >::sgamma().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Gamma< T, IRNG, stateTag >::ranf () [inline, protected]
Referenced by Gamma< T, IRNG, stateTag >::random().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> void Gamma< T, IRNG, stateTag >::setMean (T mean) [inline]
Referenced by ChiSquare< T, IRNG, stateTag >::setDF().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Gamma< T, IRNG, stateTag >::sexpo () [inline, protected]
Referenced by Gamma< T, IRNG, stateTag >::random().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Gamma< T, IRNG, stateTag >::snorm () [inline, protected]
Referenced by Gamma< T, IRNG, stateTag >::random().
Member Data Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Gamma< T, IRNG, stateTag >::a [protected]
Referenced by Gamma< T, IRNG, stateTag >::random().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> ExponentialUnit<T,IRNG,sharedState> Gamma< T, IRNG, stateTag >::exponential_ [protected]
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> NormalUnit<T,IRNG,sharedState> Gamma< T, IRNG, stateTag >::normal_ [protected]
The documentation for this class was generated from the following file:
random/gamma.h