blitz: MersenneTwister Class Reference
MersenneTwister Class Reference
#include <rand-mt.h>
Classes
struct BitMixer
class mt_state
Public Types
typedef mt_state T_state
Public Member Functions
MersenneTwister ()
void seed (twist_int seed=reference_seed)
void reload (void)
twist_int random (void)
MersenneTwister ()
MersenneTwister (twist_int aa, twist_int bb, twist_int cc)
MersenneTwister (twist_int initial_seed)
MersenneTwister (twist_int aa, twist_int bb, twist_int cc, twist_int initial_seed)
void seed (twist_int seed=reference_seed)
void seed (State seed_vector)
void reload (void)
twist_int random (void)
T_state getState () const
std::string getStateString () const
void setState (const T_state &s)
void setState (const std::string &s)
Private Types
enum { N = 624, PF = 397, reference_seed = 4357 }
enum { N = 624, PF = 397, reference_seed = 4357 }
typedef unsigned int twist_int
typedef vector< twist_int > State
typedef State::iterator Iter
typedef vector< twist_int > State
typedef State::size_type SizeType
typedef State::iterator Iter
Private Member Functions
void initialize ()
Private Attributes
State S
Iter I
BitMixer twist_
const twist_int b_
const twist_int c_
Member Typedef Documentation
typedef State::iterator MersenneTwister::Iter [private]
typedef State::iterator MersenneTwister::Iter [private]
typedef State::size_type MersenneTwister::SizeType [private]
typedef vector<twist_int> MersenneTwister::State [private]
typedef vector<twist_int> MersenneTwister::State [private]
typedef mt_state MersenneTwister::T_state
typedef unsigned int MersenneTwister::twist_int [private]
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
N
PF
reference_seed
anonymous enum [private]
Enumerator:
N
PF
reference_seed
Constructor & Destructor Documentation
MersenneTwister::MersenneTwister () [inline]
MersenneTwister::MersenneTwister () [inline]
References initialize(), and seed().
MersenneTwister::MersenneTwister (twist_int aa, twist_int bb, twist_int cc) [inline]
References initialize(), and seed().
MersenneTwister::MersenneTwister (twist_int initial_seed) [inline]
References initialize(), and seed().
MersenneTwister::MersenneTwister (twist_int aa, twist_int bb, twist_int cc, twist_int initial_seed) [inline]
References initialize(), and seed().
Member Function Documentation
T_state MersenneTwister::getState () const [inline]
References I, and S.
std::string MersenneTwister::getStateString () const [inline]
References I, and S.
void MersenneTwister::initialize () [inline, private]
References I, N, and S.
Referenced by MersenneTwister().
twist_int MersenneTwister::random (void) [inline]
References b_, c_, I, reload(), and S.
twist_int MersenneTwister::random (void) [inline]
Referenced by MersenneTwisterDouble::random().
void MersenneTwister::reload (void) [inline]
References I, N, PF, S, and twist_.
void MersenneTwister::reload (void) [inline]
Referenced by random(), and seed().
void MersenneTwister::seed (State seed_vector) [inline]
References i, j, k, n, N, reload(), S, and seed().
void MersenneTwister::seed (twist_int seed = reference_seed) [inline]
References reference_seed, reload(), S, and seed().
void MersenneTwister::seed (twist_int seed = reference_seed) [inline]
References j, and s.
Referenced by MersenneTwister(), MersenneTwisterDouble::randomize(), and seed().
void MersenneTwister::setState (const std::string & s) [inline]
References setState().
void MersenneTwister::setState (const T_state & s) [inline]
References MersenneTwister::mt_state::I, I, MersenneTwister::mt_state::S, and S.
Referenced by setState().
Member Data Documentation
const twist_int MersenneTwister::b_ [private]
Referenced by random().
const twist_int MersenneTwister::c_ [private]
Referenced by random().
Iter MersenneTwister::I [private]
Referenced by getState(), getStateString(), initialize(), random(), reload(), and setState().
State MersenneTwister::S [private]
Referenced by getState(), getStateString(), initialize(), random(), reload(), seed(), and setState().
BitMixer MersenneTwister::twist_ [private]
Referenced by reload().
The documentation for this class was generated from the following files:
blitz/rand-mt.h
random/mt.h