blitz: MemoryBlock< P_type > Class Template Reference
MemoryBlock< P_type > Class Template Reference
#include <memblock.h>
Public Types
typedef P_type T_type
Protected Member Functions
MemoryBlock ()
MemoryBlock (sizeType items)
MemoryBlock (sizeType length, T_type *data)
virtual ~MemoryBlock ()
bool doLock (bool lockingPolicy)
void addReference ()
T_type *restrict data ()
const T_type *restrict data () const
T_type *& dataBlockAddress ()
sizeType length () const
int removeReference ()
int references () const
void allocate (sizeType length)
void deallocate ()
Private Member Functions
MemoryBlock (const MemoryBlock< T_type > &)
void operator= (const MemoryBlock< T_type > &)
Private Attributes
T_type *restrict data_
T_type * dataBlockAddress_
volatile int references_
bool mutexLocking_
sizeType length_
Friends
class MemoryBlockReference< P_type >
template<typename P_type>
class MemoryBlock< P_type >
Member Typedef Documentation
template<typename P_type> typedef P_type MemoryBlock< P_type >::T_type
Constructor & Destructor Documentation
template<typename P_type> MemoryBlock< P_type >::MemoryBlock () [inline, protected]
template<typename P_type> MemoryBlock< P_type >::MemoryBlock (sizeType items) [inline, explicit, protected]
template<typename P_type> MemoryBlock< P_type >::MemoryBlock (sizeType length, T_type * data) [inline, protected]
template<typename P_type> virtual MemoryBlock< P_type >::~MemoryBlock () [inline, protected, virtual]
template<typename P_type> MemoryBlock< P_type >::MemoryBlock (const MemoryBlock< T_type > &) [inline, private]
Member Function Documentation
template<typename P_type> void MemoryBlock< P_type >::addReference () [inline, protected]
Referenced by MemoryBlockReference< int >::addReference(), MemoryBlockReference< int >::changeBlock(), MemoryBlockReference< int >::changeToNullBlock(), MemoryBlockReference< int >::MemoryBlockReference(), and MemoryBlockReference< int >::newBlock().
template<typename P_type> void MemoryBlock< P_type >::allocate (sizeType length) [inline, protected]
Referenced by MemoryBlock< T_type >::MemoryBlock().
template<typename P_type> const T_type* restrict MemoryBlock< P_type >::data () const [inline, protected]
template<typename P_type> T_type* restrict MemoryBlock< P_type >::data () [inline, protected]
Referenced by MemoryBlockReference< int >::MemoryBlockReference(), and MemoryBlockReference< int >::newBlock().
template<typename P_type> T_type*& MemoryBlock< P_type >::dataBlockAddress () [inline, protected]
template<typename P_type> void MemoryBlock< P_type >::deallocate () [protected]
Referenced by MemoryBlock< T_type >::~MemoryBlock().
template<typename P_type> bool MemoryBlock< P_type >::doLock (bool lockingPolicy) [inline, protected]
Referenced by MemoryBlockReference< int >::lockReferenceCount().
template<typename P_type> sizeType MemoryBlock< P_type >::length () const [inline, protected]
template<typename P_type> void MemoryBlock< P_type >::operator= (const MemoryBlock< T_type > &) [inline, private]
template<typename P_type> int MemoryBlock< P_type >::references () const [inline, protected]
Referenced by MemoryBlockReference< int >::numReferences().
template<typename P_type> int MemoryBlock< P_type >::removeReference () [inline, protected]
Referenced by MemoryBlockReference< int >::blockRemoveReference(), and MemoryBlockReference< int >::removeReference().
Friends And Related Function Documentation
template<typename P_type> friend class MemoryBlockReference< P_type > [friend]
Member Data Documentation
template<typename P_type> T_type* restrict MemoryBlock< P_type >::data_ [private]
Referenced by MemoryBlock< T_type >::data(), and MemoryBlock< T_type >::MemoryBlock().
template<typename P_type> T_type* MemoryBlock< P_type >::dataBlockAddress_ [private]
Referenced by MemoryBlock< T_type >::addReference(), MemoryBlock< T_type >::dataBlockAddress(), MemoryBlock< T_type >::MemoryBlock(), MemoryBlock< T_type >::removeReference(), and MemoryBlock< T_type >::~MemoryBlock().
template<typename P_type> sizeType MemoryBlock< P_type >::length_ [private]
Referenced by MemoryBlock< T_type >::addReference(), MemoryBlock< T_type >::length(), MemoryBlock< T_type >::MemoryBlock(), MemoryBlock< T_type >::removeReference(), and MemoryBlock< T_type >::~MemoryBlock().
template<typename P_type> bool MemoryBlock< P_type >::mutexLocking_ [private]
Referenced by MemoryBlock< T_type >::addReference(), MemoryBlock< T_type >::doLock(), MemoryBlock< T_type >::MemoryBlock(), MemoryBlock< T_type >::references(), and MemoryBlock< T_type >::removeReference().
template<typename P_type> volatile int MemoryBlock< P_type >::references_ [private]
Referenced by MemoryBlock< T_type >::addReference(), MemoryBlock< T_type >::doLock(), MemoryBlock< T_type >::MemoryBlock(), MemoryBlock< T_type >::references(), and MemoryBlock< T_type >::removeReference().
The documentation for this class was generated from the following file:
blitz/memblock.h