blitz: UniformOpen< T, IRNG, stateTag > Class Template Reference
UniformOpen< T, IRNG, stateTag > Class Template Reference
#include <uniform.h>
Public Types
typedef T T_numtype
Public Member Functions
UniformOpen ()
UniformOpen (unsigned int i)
T random ()
T getUniform ()
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState>
class UniformOpen< T, IRNG, stateTag >
Member Typedef Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> typedef T UniformOpen< T, IRNG, stateTag >::T_numtype
Reimplemented in Normal< BZ_TEMPLATE_DEFAULT >, Beta< T, IRNG, stateTag >, ChiSquare< T, IRNG, stateTag >, ExponentialUnit< T, IRNG, stateTag >, Exponential< T, IRNG, stateTag >, Gamma< T, IRNG, stateTag >, NormalUnit< T, IRNG, stateTag >, Normal< BZ_TEMPLATE_DEFAULT >, ExponentialUnit< T, IRNG, stateTag >, ExponentialUnit< T, IRNG, sharedState >, Gamma< T, IRNG, stateTag >, NormalUnit< T, IRNG, stateTag >, and NormalUnit< T, IRNG, sharedState >.
Constructor & Destructor Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> UniformOpen< T, IRNG, stateTag >::UniformOpen () [inline]
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> UniformOpen< T, IRNG, stateTag >::UniformOpen (unsigned int i) [inline]
Member Function Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T UniformOpen< T, IRNG, stateTag >::getUniform () [inline]
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T UniformOpen< T, IRNG, stateTag >::random (void) [inline]
Reimplemented in Normal< BZ_TEMPLATE_DEFAULT >, Beta< T, IRNG, stateTag >, ChiSquare< T, IRNG, stateTag >, ExponentialUnit< T, IRNG, stateTag >, Exponential< T, IRNG, stateTag >, Gamma< T, IRNG, stateTag >, NormalUnit< T, IRNG, stateTag >, Normal< BZ_TEMPLATE_DEFAULT >, ExponentialUnit< T, IRNG, stateTag >, ExponentialUnit< T, IRNG, sharedState >, Gamma< T, IRNG, stateTag >, NormalUnit< T, IRNG, stateTag >, and NormalUnit< T, IRNG, sharedState >.
Referenced by UniformOpen< T,IRNG,sharedState >::getUniform(), UniformOpen< T,IRNG,sharedState >::random(), Gamma< T, IRNG, stateTag >::ranf(), and Beta< T, IRNG, stateTag >::ranf().
The documentation for this class was generated from the following file:
random/uniform.h