blitz: ReduceMean< P_sourcetype, P_resulttype > Class Template Reference
ReduceMean< P_sourcetype, P_resulttype > Class Template Reference
#include <reduce.h>
Public Types
typedef P_sourcetype T_sourcetype
typedef P_resulttype T_resulttype
typedef T_resulttype T_numtype
Public Member Functions
ReduceMean ()
bool operator() (const T_sourcetype &x, const int=0) const
T_resulttype result (const int count) const
void reset () const
Static Public Member Functions
static const char * name ()
Static Public Attributes
static const bool needIndex = false
static const bool needInit = false
Protected Attributes
T_resulttype sum_
template<typename P_sourcetype, typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)>
class ReduceMean< P_sourcetype, P_resulttype >
Member Typedef Documentation
template<typename P_sourcetype , typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)> typedef T_resulttype ReduceMean< P_sourcetype, P_resulttype >::T_numtype
template<typename P_sourcetype , typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)> typedef P_resulttype ReduceMean< P_sourcetype, P_resulttype >::T_resulttype
template<typename P_sourcetype , typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)> typedef P_sourcetype ReduceMean< P_sourcetype, P_resulttype >::T_sourcetype
Constructor & Destructor Documentation
template<typename P_sourcetype , typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)> ReduceMean< P_sourcetype, P_resulttype >::ReduceMean () [inline]
Member Function Documentation
template<typename P_sourcetype , typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)> static const char* ReduceMean< P_sourcetype, P_resulttype >::name () [inline, static]
template<typename P_sourcetype , typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)> bool ReduceMean< P_sourcetype, P_resulttype >::operator() (const T_sourcetype & x, const int = 0) const [inline]
References ReduceMean< P_sourcetype, P_resulttype >::sum_.
template<typename P_sourcetype , typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)> void ReduceMean< P_sourcetype, P_resulttype >::reset () const [inline]
References ReduceMean< P_sourcetype, P_resulttype >::sum_.
template<typename P_sourcetype , typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)> T_resulttype ReduceMean< P_sourcetype, P_resulttype >::result (const int count) const [inline]
References ReduceMean< P_sourcetype, P_resulttype >::sum_.
Member Data Documentation
template<typename P_sourcetype , typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)> const bool ReduceMean< P_sourcetype, P_resulttype >::needIndex = false [static]
template<typename P_sourcetype , typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)> const bool ReduceMean< P_sourcetype, P_resulttype >::needInit = false [static]
template<typename P_sourcetype , typename P_resulttype = BZ_FLOATTYPE(P_sourcetype)> T_resulttype ReduceMean< P_sourcetype, P_resulttype >::sum_ [mutable, protected]
Referenced by ReduceMean< P_sourcetype, P_resulttype >::operator()(), ReduceMean< P_sourcetype, P_resulttype >::reset(), and ReduceMean< P_sourcetype, P_resulttype >::result().
The documentation for this class was generated from the following file:
blitz/reduce.h