blitz: ColumnMajor Class Reference
ColumnMajor Class Reference
#include <matgen.h>
Public Member Functions
ColumnMajor ()
ColumnMajor (unsigned rows, unsigned cols)
unsigned coordToOffset (unsigned i, unsigned j) const
template<typename T_numtype >
T_numtype get (const T_numtype *restrict data, unsigned i, unsigned j) const
template<typename T_numtype >
T_numtype & get (T_numtype *restrict data, unsigned i, unsigned j)
Constructor & Destructor Documentation
ColumnMajor::ColumnMajor () [inline]
ColumnMajor::ColumnMajor (unsigned rows, unsigned cols) [inline]
Member Function Documentation
unsigned ColumnMajor::coordToOffset (unsigned i, unsigned j) const [inline]
References AsymmetricMatrix::rows_.
Referenced by get().
template<typename T_numtype > T_numtype& ColumnMajor::get (T_numtype *restrict data, unsigned i, unsigned j) [inline]
References coordToOffset(), i, AsymmetricMatrix::inRange(), and j.
template<typename T_numtype > T_numtype ColumnMajor::get (const T_numtype *restrict data, unsigned i, unsigned j) const [inline]
References coordToOffset(), i, AsymmetricMatrix::inRange(), and j.
The documentation for this class was generated from the following file:
blitz/matgen.h