blitz: Range Class Reference
Range Class Reference
#include <range.h>
Public Types
typedef int T_numtype
typedef unsigned int T_sizetype
Public Member Functions
Range ()
Range (T_numtype slicePosition)
Range (T_numtype first, T_numtype last, diffType stride=1)
T_numtype first (T_numtype lowRange=0) const
T_numtype last (T_numtype highRange=0) const
T_sizetype length (int=0) const
diffType stride () const
bool isAscendingContiguous () const
void setRange (T_numtype first, T_numtype last, diffType stride=1)
bool isUnitStride () const
Range operator- (T_numtype shift) const
Range operator+ (T_numtype shift) const
T_numtype operator[] (T_sizetype i) const
T_numtype operator() (T_sizetype i) const
bool _bz_hasFastAccess () const
int _bz_fastAccess (unsigned int i) const
unsigned int _bz_suggestLength () const
_bz_VecExpr< Range > _bz_asVecExpr () const
Static Public Member Functions
static Range all ()
Static Public Attributes
static const int _bz_staticLengthCount = 0
static const int _bz_dynamicLengthCount = 0
static const int _bz_staticLength = 0
Private Attributes
T_numtype first_
T_numtype last_
diffType stride_
Friends
ostream & operator<< (ostream &os, const Range &range)
Member Typedef Documentation
typedef int Range::T_numtype
typedef unsigned int Range::T_sizetype
Constructor & Destructor Documentation
Range::Range () [inline]
References fromStart, and toEnd.
Range::Range (T_numtype slicePosition) [inline, explicit]
Range::Range (T_numtype first, T_numtype last, diffType stride = 1) [inline]
References fromStart, and toEnd.
Member Function Documentation
_bz_VecExpr<Range> Range::_bz_asVecExpr () const [inline]
int Range::_bz_fastAccess (unsigned int i) const [inline]
bool Range::_bz_hasFastAccess () const [inline]
unsigned int Range::_bz_suggestLength () const [inline]
Referenced by Vector< T_numtype >::Vector().
static Range Range::all () [inline, static]
References fromStart, and toEnd.
T_numtype Range::first (T_numtype lowRange = 0) const [inline]
References fromStart.
Referenced by Array< P_numtype, N_rank >::Array(), and Vector< T_numtype >::Vector().
bool Range::isAscendingContiguous () const [inline]
Referenced by Array< P_numtype, N_rank >::Array().
bool Range::isUnitStride () const [inline]
T_numtype Range::last (T_numtype highRange = 0) const [inline]
References toEnd.
Referenced by Vector< T_numtype >::Vector().
T_sizetype Range::length (int = 0) const [inline]
References fromStart, and toEnd.
Referenced by Array< P_numtype, N_rank >::Array().
T_numtype Range::operator() (T_sizetype i) const [inline]
Range Range::operator+ (T_numtype shift) const [inline]
References fromStart, and toEnd.
Range Range::operator- (T_numtype shift) const [inline]
References fromStart, and toEnd.
T_numtype Range::operator[] (T_sizetype i) const [inline]
void Range::setRange (T_numtype first, T_numtype last, diffType stride = 1) [inline]
diffType Range::stride () const [inline]
Referenced by Vector< T_numtype >::Vector().
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const Range & range) [friend]
Member Data Documentation
const int Range::_bz_dynamicLengthCount = 0 [static]
const int Range::_bz_staticLength = 0 [static]
const int Range::_bz_staticLengthCount = 0 [static]
T_numtype Range::first_ [private]
T_numtype Range::last_ [private]
diffType Range::stride_ [private]
The documentation for this class was generated from the following file:
blitz/range.h