blitz: VectorPick< P_numtype > Class Template Reference
VectorPick< P_numtype > Class Template Reference
#include <vecpick.h>
Public Types
typedef P_numtype T_numtype
typedef Vector< T_numtype > T_vector
typedef Vector< int > T_indexVector
typedef VectorPick< T_numtype > T_pick
typedef VectorPickIter< T_numtype > T_iterator
typedef VectorPickIterConst
< T_numtype > T_constIterator
Public Member Functions
VectorPick (T_vector &vector, T_indexVector &indexarg)
VectorPick (const T_pick &vecpick)
VectorPick (T_pick &vecpick, Range r)
T_iterator beginFast ()
T_constIterator beginFast () const
T_indexVector & indexSet ()
const T_indexVector & indexSet () const
int length () const
void setVector (Vector< T_numtype > &x)
void setIndex (Vector< int > &index)
T_vector & vector ()
const T_vector & vector () const
int _bz_suggestLength () const
bool _bz_hasFastAccess () const
T_numtype & _bz_fastAccess (int i)
T_numtype _bz_fastAccess (int i) const
_bz_VecExpr< T_constIterator > _bz_asVecExpr () const
T_numtype operator() (int i) const
T_numtype & operator() (int i)
T_numtype operator[] (int i) const
T_numtype & operator[] (int i)
T_pick operator() (Range r)
T_pick operator[] (Range r)
T_pick & operator= (T_numtype)
T_pick & operator+= (T_numtype)
T_pick & operator-= (T_numtype)
T_pick & operator*= (T_numtype)
T_pick & operator/= (T_numtype)
T_pick & operator%= (T_numtype)
T_pick & operator^= (T_numtype)
T_pick & operator&= (T_numtype)
T_pick & operator|= (T_numtype)
T_pick & operator>>= (int)
T_pick & operator<<= (int)
template<typename P_numtype2 >
T_pick & operator= (const Vector< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator+= (const Vector< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator-= (const Vector< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator*= (const Vector< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator/= (const Vector< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator%= (const Vector< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator^= (const Vector< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator&= (const Vector< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator|= (const Vector< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator>>= (const Vector< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator<<= (const Vector< P_numtype2 > &)
template<typename P_expr >
T_pick & operator= (_bz_VecExpr< P_expr >)
template<typename P_expr >
T_pick & operator+= (_bz_VecExpr< P_expr >)
template<typename P_expr >
T_pick & operator-= (_bz_VecExpr< P_expr >)
template<typename P_expr >
T_pick & operator*= (_bz_VecExpr< P_expr >)
template<typename P_expr >
T_pick & operator/= (_bz_VecExpr< P_expr >)
template<typename P_expr >
T_pick & operator%= (_bz_VecExpr< P_expr >)
template<typename P_expr >
T_pick & operator^= (_bz_VecExpr< P_expr >)
template<typename P_expr >
T_pick & operator&= (_bz_VecExpr< P_expr >)
template<typename P_expr >
T_pick & operator|= (_bz_VecExpr< P_expr >)
template<typename P_expr >
T_pick & operator>>= (_bz_VecExpr< P_expr >)
template<typename P_expr >
T_pick & operator<<= (_bz_VecExpr< P_expr >)
T_pick & operator= (Range)
T_pick & operator+= (Range)
T_pick & operator-= (Range)
T_pick & operator*= (Range)
T_pick & operator/= (Range)
T_pick & operator%= (Range)
T_pick & operator^= (Range)
T_pick & operator&= (Range)
T_pick & operator|= (Range)
T_pick & operator>>= (Range)
T_pick & operator<<= (Range)
template<typename P_numtype2 >
T_pick & operator= (const VectorPick< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator+= (const VectorPick< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator-= (const VectorPick< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator*= (const VectorPick< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator/= (const VectorPick< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator%= (const VectorPick< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator^= (const VectorPick< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator&= (const VectorPick< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator|= (const VectorPick< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator>>= (const VectorPick< P_numtype2 > &)
template<typename P_numtype2 >
T_pick & operator<<= (const VectorPick< P_numtype2 > &)
template<typename P_distribution >
T_pick & operator= (Random< P_distribution > &random)
template<typename P_distribution >
T_pick & operator+= (Random< P_distribution > &random)
template<typename P_distribution >
T_pick & operator-= (Random< P_distribution > &random)
template<typename P_distribution >
T_pick & operator*= (Random< P_distribution > &random)
template<typename P_distribution >
T_pick & operator/= (Random< P_distribution > &random)
template<typename P_distribution >
T_pick & operator%= (Random< P_distribution > &random)
template<typename P_distribution >
T_pick & operator^= (Random< P_distribution > &random)
template<typename P_distribution >
T_pick & operator&= (Random< P_distribution > &random)
template<typename P_distribution >
T_pick & operator|= (Random< P_distribution > &random)
Private Member Functions
VectorPick ()
template<typename P_expr , typename P_updater >
void _bz_assign (P_expr, P_updater)
Private Attributes
T_vector vector_
T_indexVector index_
template<typename P_numtype>
class VectorPick< P_numtype >
Member Typedef Documentation
template<typename P_numtype> typedef VectorPickIterConst<T_numtype> VectorPick< P_numtype >::T_constIterator
template<typename P_numtype> typedef Vector<int> VectorPick< P_numtype >::T_indexVector
template<typename P_numtype> typedef VectorPickIter<T_numtype> VectorPick< P_numtype >::T_iterator
template<typename P_numtype> typedef P_numtype VectorPick< P_numtype >::T_numtype
template<typename P_numtype> typedef VectorPick<T_numtype> VectorPick< P_numtype >::T_pick
template<typename P_numtype> typedef Vector<T_numtype> VectorPick< P_numtype >::T_vector
Constructor & Destructor Documentation
template<typename P_numtype> VectorPick< P_numtype >::VectorPick (T_vector & vector, T_indexVector & indexarg) [inline]
template<typename P_numtype> VectorPick< P_numtype >::VectorPick (const T_pick & vecpick) [inline]
template<typename P_numtype> VectorPick< P_numtype >::VectorPick (T_pick & vecpick, Range r) [inline]
template<typename P_numtype> VectorPick< P_numtype >::VectorPick () [inline, private]
Member Function Documentation
template<typename P_numtype> template<typename P_expr , typename P_updater > void VectorPick< P_numtype >::_bz_assign (P_expr , P_updater) [inline, private]
template<typename P_numtype> _bz_VecExpr<T_constIterator> VectorPick< P_numtype >::_bz_asVecExpr () const [inline]
template<typename P_numtype> T_numtype VectorPick< P_numtype >::_bz_fastAccess (int i) const [inline]
template<typename P_numtype> T_numtype& VectorPick< P_numtype >::_bz_fastAccess (int i) [inline]
template<typename P_numtype> bool VectorPick< P_numtype >::_bz_hasFastAccess () const [inline]
template<typename P_numtype> int VectorPick< P_numtype >::_bz_suggestLength () const [inline]
template<typename P_numtype> T_constIterator VectorPick< P_numtype >::beginFast () const [inline]
template<typename P_numtype> T_iterator VectorPick< P_numtype >::beginFast () [inline]
template<typename P_numtype> const T_indexVector& VectorPick< P_numtype >::indexSet () const [inline]
template<typename P_numtype> T_indexVector& VectorPick< P_numtype >::indexSet () [inline]
Referenced by VectorPickIter< P_numtype >::VectorPickIter(), and VectorPickIterConst< P_numtype >::VectorPickIterConst().
template<typename P_numtype> int VectorPick< P_numtype >::length () const [inline]
template<typename P_numtype> template<typename P_distribution > T_pick& VectorPick< P_numtype >::operator%= (Random< P_distribution > & random) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator%= (const VectorPick< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator%= (Range)
template<typename P_numtype> template<typename P_expr > T_pick& VectorPick< P_numtype >::operator%= (_bz_VecExpr< P_expr >) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator%= (const Vector< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator%= (T_numtype)
template<typename P_numtype> template<typename P_distribution > T_pick& VectorPick< P_numtype >::operator&= (Random< P_distribution > & random) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator&= (const VectorPick< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator&= (Range)
template<typename P_numtype> template<typename P_expr > T_pick& VectorPick< P_numtype >::operator&= (_bz_VecExpr< P_expr >) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator&= (const Vector< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator&= (T_numtype)
template<typename P_numtype> T_pick VectorPick< P_numtype >::operator() (Range r) [inline]
template<typename P_numtype> T_numtype& VectorPick< P_numtype >::operator() (int i) [inline]
template<typename P_numtype> T_numtype VectorPick< P_numtype >::operator() (int i) const [inline]
template<typename P_numtype> template<typename P_distribution > T_pick& VectorPick< P_numtype >::operator*= (Random< P_distribution > & random) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator*= (const VectorPick< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator*= (Range)
template<typename P_numtype> template<typename P_expr > T_pick& VectorPick< P_numtype >::operator*= (_bz_VecExpr< P_expr >) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator*= (const Vector< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator*= (T_numtype)
template<typename P_numtype> template<typename P_distribution > T_pick& VectorPick< P_numtype >::operator+= (Random< P_distribution > & random) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator+= (const VectorPick< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator+= (Range)
template<typename P_numtype> template<typename P_expr > T_pick& VectorPick< P_numtype >::operator+= (_bz_VecExpr< P_expr >) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator+= (const Vector< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator+= (T_numtype)
template<typename P_numtype> template<typename P_distribution > T_pick& VectorPick< P_numtype >::operator-= (Random< P_distribution > & random) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator-= (const VectorPick< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator-= (Range)
template<typename P_numtype> template<typename P_expr > T_pick& VectorPick< P_numtype >::operator-= (_bz_VecExpr< P_expr >) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator-= (const Vector< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator-= (T_numtype)
template<typename P_numtype> template<typename P_distribution > T_pick& VectorPick< P_numtype >::operator/= (Random< P_distribution > & random) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator/= (const VectorPick< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator/= (Range)
template<typename P_numtype> template<typename P_expr > T_pick& VectorPick< P_numtype >::operator/= (_bz_VecExpr< P_expr >) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator/= (const Vector< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator/= (T_numtype)
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator<<= (const VectorPick< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator<<= (Range)
template<typename P_numtype> template<typename P_expr > T_pick& VectorPick< P_numtype >::operator<<= (_bz_VecExpr< P_expr >) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator<<= (const Vector< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator<<= (int)
template<typename P_numtype> template<typename P_distribution > T_pick& VectorPick< P_numtype >::operator= (Random< P_distribution > & random) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator= (const VectorPick< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator= (Range)
template<typename P_numtype> template<typename P_expr > T_pick& VectorPick< P_numtype >::operator= (_bz_VecExpr< P_expr >) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator= (const Vector< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator= (T_numtype)
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator>>= (const VectorPick< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator>>= (Range)
template<typename P_numtype> template<typename P_expr > T_pick& VectorPick< P_numtype >::operator>>= (_bz_VecExpr< P_expr >) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator>>= (const Vector< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator>>= (int)
template<typename P_numtype> T_pick VectorPick< P_numtype >::operator[] (Range r) [inline]
template<typename P_numtype> T_numtype& VectorPick< P_numtype >::operator[] (int i) [inline]
template<typename P_numtype> T_numtype VectorPick< P_numtype >::operator[] (int i) const [inline]
template<typename P_numtype> template<typename P_distribution > T_pick& VectorPick< P_numtype >::operator^= (Random< P_distribution > & random) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator^= (const VectorPick< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator^= (Range)
template<typename P_numtype> template<typename P_expr > T_pick& VectorPick< P_numtype >::operator^= (_bz_VecExpr< P_expr >) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator^= (const Vector< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator^= (T_numtype)
template<typename P_numtype> template<typename P_distribution > T_pick& VectorPick< P_numtype >::operator|= (Random< P_distribution > & random) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator|= (const VectorPick< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator|= (Range)
template<typename P_numtype> template<typename P_expr > T_pick& VectorPick< P_numtype >::operator|= (_bz_VecExpr< P_expr >) [inline]
template<typename P_numtype> template<typename P_numtype2 > T_pick& VectorPick< P_numtype >::operator|= (const Vector< P_numtype2 > &) [inline]
template<typename P_numtype> T_pick& VectorPick< P_numtype >::operator|= (T_numtype)
template<typename P_numtype> void VectorPick< P_numtype >::setIndex (Vector< int > & index) [inline]
template<typename P_numtype> void VectorPick< P_numtype >::setVector (Vector< T_numtype > & x) [inline]
template<typename P_numtype> const T_vector& VectorPick< P_numtype >::vector () const [inline]
template<typename P_numtype> T_vector& VectorPick< P_numtype >::vector () [inline]
Referenced by VectorPickIter< P_numtype >::VectorPickIter(), and VectorPickIterConst< P_numtype >::VectorPickIterConst().
Member Data Documentation
template<typename P_numtype> T_indexVector VectorPick< P_numtype >::index_ [private]
template<typename P_numtype> T_vector VectorPick< P_numtype >::vector_ [private]
The documentation for this class was generated from the following file:
blitz/vecpick.h