blitz: MersenneTwister::BitMixer Struct Reference
MersenneTwister::BitMixer Struct Reference
Public Types
enum { K = 0x9908b0df }
Public Member Functions
BitMixer ()
twist_int high_mask (twist_int s1) const
twist_int operator() (twist_int s1)
BitMixer ()
BitMixer (twist_int k)
twist_int low_mask (twist_int s1) const
twist_int high_mask (twist_int s1) const
twist_int operator() (twist_int s1)
Public Attributes
twist_int s0
const twist_int K
Friends
twist_int low_mask (twist_int s1)
Member Enumeration Documentation
anonymous enum
Enumerator:
K
Constructor & Destructor Documentation
MersenneTwister::BitMixer::BitMixer () [inline]
MersenneTwister::BitMixer::BitMixer () [inline]
MersenneTwister::BitMixer::BitMixer (twist_int k) [inline]
Member Function Documentation
twist_int MersenneTwister::BitMixer::high_mask (twist_int s1) const [inline]
References s0.
twist_int MersenneTwister::BitMixer::high_mask (twist_int s1) const [inline]
Referenced by operator()().
twist_int MersenneTwister::BitMixer::low_mask (twist_int s1) const [inline]
References K.
twist_int MersenneTwister::BitMixer::operator() (twist_int s1) [inline]
References high_mask(), low_mask, r, and s0.
twist_int MersenneTwister::BitMixer::operator() (twist_int s1) [inline]
References r.
Friends And Related Function Documentation
twist_int low_mask (twist_int s1) [friend]
Referenced by operator()().
Member Data Documentation
const twist_int MersenneTwister::BitMixer::K
twist_int MersenneTwister::BitMixer::s0
Referenced by high_mask(), and operator()().
The documentation for this struct was generated from the following files:
blitz/rand-mt.h
random/mt.h