#!/usr/bin/awk -f

/;/ {
    t = tab($0)
    v = $2
    sub(/;/, "", v)
    sub(/\*/, "", v)
    sub(/\[.*\]/, "", v)
    printf "%s%s = q->%s;\n", t, v, v
}

function tab(s)
{
    sub(/[^\t ].*/, "", s)
    return s
}

function trim(s)
{
    sub(/^[\t ]*/, "", s)
    sub(/[\t ]*$/, "", s)
    return s
}
