#!/usr/bin/awk -f

NF {
    t = tab($0)
    match($0, /[a-zA-Z_][a-zA-Z0-9_]*;/)
    v = substr($0, RSTART, RLENGTH - 1)
    printf "%s%s = q->%s;\n", t, v, v
    next
}

{
    print
}

function tab(s)
{
    sub(/[^\t ].*/, "", s)
    return s
}

function trim(s)
{
    sub(/^[\t ]*/, "", s)
    sub(/[\t ]*$/, "", s)
    return s
}
