#!/usr/bin/awk -f

BEGIN {
    printf "# generate by scripts/dep\n"
}

sub(/^[\t ]*#[\t ]*include[\t ]*/, "") && sub(/^"/, "") && sub(/"[\t ]*/, "") {
    if (!filep($0)) {
	printf "%s:%d: error: no such file '%s'\n", FILENAME, FNR, $0 | "cat >&2"
	exit(1)
    }
    sub(/\.c$/, ".o", FILENAME)
    print FILENAME ": " $0 | "sort"
}

function filep(path, aux, rc) {
  rc = getline aux < path
  close(path)
  return rc >= 0
}
