#!/bin/sh

: ${AWK=awk}

"$AWK" '
BEGIN { x0 = y0 = 1; a = 0.6; b = 0.4; T = 0 }
NR == 1 { print; next }
NR == 2 { print; next }
{
    $1 = $1
    x = $2; y = $3
    if (ellipse(x, y)) $1 = "Water"; else $1 = "Air"
    $8 = T
    print
}
function ellipse(x, y) {
    x -= x0; y -= y0
    return (x/a)^2 + (y/b)^2 < 1
}
' "$@"
