#!/bin/sh

VERSION_CONTROL=none
export VERSION_CONTROL

#      --pointer-align-right
exec indent \
     -kr\
     --blank-lines-after-declarations\
     --procnames-start-lines\
     --no-tabs\
     --pointer-align-right\
     --tab-size 4\
     "$@"
