all: create_IC create_ICq1D create_ICq1D_mConst create_ICq1D_SpaceConst

create_IC: create_IC.cpp

create_ICq1D: create_ICq1D.cpp

create_ICq1D_mConst: create_ICq1D_mConst.cpp

create_ICq1D_SpaceConst: create_ICq1D_SpaceConst.cpp

.PHONY: clean

clean:
	-rm create_IC
	-rm create_ICq1D
	-rm create_ICq1D_mConst
	-rm create_ICq1D_SpaceConst

