#!/bin/bash

# update doxygen documentation of github
# http://slitvinov.github.io/sph-blitz/index.html

cd src
doxygen
cd html
git commit -a -m "Autogenerated documentation"
git push origin gh-pages
