# generate by ../scripts/dep
boundary.o: inc/boundary.h
boundary.o: inc/err.h
boundary.o: inc/ini.h
boundary.o: inc/list.h
boundary.o: inc/macro.h
boundary.o: inc/material.h
boundary.o: inc/particle.h
diag.o: inc/diag.h
diag.o: inc/err.h
diag.o: inc/glbfunc.h
diag.o: inc/ini.h
diag.o: inc/list.h
diag.o: inc/macro.h
diag.o: inc/manager.h
diag.o: inc/material.h
diag.o: inc/mls.h
diag.o: inc/particle.h
diag.o: inc/vv.h
diag.o: inc/vv.h
err.o: inc/err.h
glbfunc.o: inc/glbfunc.h
hydro.o: inc/boundary.h
hydro.o: inc/err.h
hydro.o: inc/force.h
hydro.o: inc/glbfunc.h
hydro.o: inc/hydro.h
hydro.o: inc/ini.h
hydro.o: inc/kernel.h
hydro.o: inc/list.h
hydro.o: inc/macro.h
hydro.o: inc/material.h
hydro.o: inc/pair.h
hydro.o: inc/particle.h
hydro.o: inc/vv.h
ini.o: inc/err.h
ini.o: inc/ini.h
kernel.o: inc/kernel.h
list.o: inc/list.h
list.o: inc/macro.h
manager.o: inc/boundary.h
manager.o: inc/err.h
manager.o: inc/glbfunc.h
manager.o: inc/ini.h
manager.o: inc/list.h
manager.o: inc/macro.h
manager.o: inc/manager.h
manager.o: inc/material.h
manager.o: inc/pair.h
manager.o: inc/particle.h
manager.o: inc/vv.h
material.o: inc/glbfunc.h
material.o: inc/material.h
mls.o: inc/err.h
mls.o: inc/glbfunc.h
mls.o: inc/kernel.h
mls.o: inc/list.h
mls.o: inc/macro.h
mls.o: inc/mls.h
mls.o: inc/particle.h
mls.o: inc/vv.h
output.o: inc/boundary.h
output.o: inc/err.h
output.o: inc/glbfunc.h
output.o: inc/ini.h
output.o: inc/list.h
output.o: inc/macro.h
output.o: inc/manager.h
output.o: inc/material.h
output.o: inc/mls.h
output.o: inc/output.h
output.o: inc/particle.h
pair.o: inc/err.h
pair.o: inc/force.h
pair.o: inc/glbfunc.h
pair.o: inc/ini.h
pair.o: inc/kernel.h
pair.o: inc/material.h
pair.o: inc/pair.h
pair.o: inc/particle.h
pair.o: inc/vv.h
pair.o: inc/wiener.h
particle.o: inc/glbfunc.h
particle.o: inc/material.h
particle.o: inc/particle.h
sph.o: inc/boundary.h
sph.o: inc/diag.h
sph.o: inc/err.h
sph.o: inc/hydro.h
sph.o: inc/ini.h
sph.o: inc/kernel.h
sph.o: inc/manager.h
sph.o: inc/material.h
sph.o: inc/mls.h
sph.o: inc/output.h
sph.o: inc/pair.h
sph.o: inc/particle.h
sph.o: inc/step.h
sph.o: inc/volume.h
sph.o: inc/wiener.h
step.o: inc/boundary.h
step.o: inc/diag.h
step.o: inc/hydro.h
step.o: inc/ini.h
step.o: inc/manager.h
step.o: inc/step.h
volume.o: inc/kernel.h
volume.o: inc/list.h
volume.o: inc/macro.h
volume.o: inc/manager.h
volume.o: inc/particle.h
volume.o: inc/volume.h
volume.o: inc/vv.h
vv.o: inc/vv.h
wiener.o: inc/wiener.h
