# generate by ../scripts/dep
boundary.o: sph/boundary.h
boundary.o: sph/err.h
boundary.o: sph/ini.h
boundary.o: sph/list.h
boundary.o: sph/macro.h
boundary.o: sph/particle.h
err.o: sph/err.h
hydro.o: sph/boundary.h
hydro.o: sph/err.h
hydro.o: sph/force.h
hydro.o: sph/hydro.h
hydro.o: sph/ini.h
hydro.o: sph/kernel.h
hydro.o: sph/list.h
hydro.o: sph/macro.h
hydro.o: sph/material.h
hydro.o: sph/pair.h
hydro.o: sph/particle.h
hydro.o: sph/vv.h
ini.o: sph/err.h
ini.o: sph/ini.h
kernel.o: sph/err.h
kernel.o: sph/kernel.h
list.o: sph/list.h
list.o: sph/macro.h
manager.o: sph/boundary.h
manager.o: sph/err.h
manager.o: sph/ini.h
manager.o: sph/list.h
manager.o: sph/macro.h
manager.o: sph/manager.h
manager.o: sph/material.h
manager.o: sph/pair.h
manager.o: sph/particle.h
manager.o: sph/vv.h
material.o: sph/material.h
output.o: sph/boundary.h
output.o: sph/err.h
output.o: sph/ini.h
output.o: sph/list.h
output.o: sph/macro.h
output.o: sph/manager.h
output.o: sph/material.h
output.o: sph/output.h
output.o: sph/particle.h
pair.o: sph/err.h
pair.o: sph/force.h
pair.o: sph/ini.h
pair.o: sph/kernel.h
pair.o: sph/material.h
pair.o: sph/pair.h
pair.o: sph/particle.h
pair.o: sph/random.h
pair.o: sph/vv.h
particle.o: sph/material.h
particle.o: sph/particle.h
random.o: sph/random.h
step.o: sph/boundary.h
step.o: sph/hydro.h
step.o: sph/ini.h
step.o: sph/manager.h
step.o: sph/step.h
volume.o: sph/kernel.h
volume.o: sph/list.h
volume.o: sph/macro.h
volume.o: sph/manager.h
volume.o: sph/particle.h
volume.o: sph/volume.h
volume.o: sph/vv.h
vv.o: sph/vv.h
