class Initiation;
class Hydrodynamics;
class ParticleManager;
class MLS;
class QuinticSpline;
class Boundary;
class Diagnose {
	double delta;
	int x_cells, y_cells;
	int hdelta;
	int number_of_materials;
	double vx_dstrb[2][101];
	double vy_dstrb[2][101];
	double rho_dstrb[2][101];
	Llist vx_list;
	Llist vy_list;
	Llist rho_list;
	int gridx;
	int gridy;
	double ***U;
	int n_average;
	void BuildDistribution(Llist*, double dstrb[2][101]);
	double ttl_m;
	double *mtl_m;
	double glb_ave_Ek;
	double *wght_cntr ;
	double *wght_v;
public:
	Diagnose(Initiation*, Hydrodynamics*);
	void SaveStates(Hydrodynamics*);
	void OutputProfile(double Time);
	void Average(ParticleManager*, MLS*, QuinticSpline*);
	void OutputAverage(double Time);
	void KineticInformation(double Time, Hydrodynamics*);
};
