struct Material;
struct Interaction;
struct Force;
struct Particle;
struct Initiation;
struct Boundary;
struct Material;
struct QuinticSpline;
struct Hydrodynamics {
    int number_of_materials;
    double gravity[2];
    double smoothinglength;
    double delta;
    double delta2;
    double delta3;
    double dt_g_vis;
    double dt_surf;
    struct List *interaction_list;
    double viscosity_max;
    double surface_max;
    struct Material *materials;
    struct Force **forces;
    struct List *particle_list;
     Hydrodynamics(Initiation *);
    ~Hydrodynamics();
    double GetTimestep();
    void AddGravity();
    void Corrector_summation(double dt);
    void Predictor_summation(double dt);
    void RandomEffects();
    void UpdateChangeRate();
    void UpdateDensity();
    void UpdatePahseMatrix(struct Boundary *);
    void UpdatePair(struct QuinticSpline *);
    void UpdatePhaseGradient(struct Boundary *);
    void UpdateRandom(double sqrtdt);
    void UpdateState();
    void UpdateSurfaceStress(struct Boundary *);
    void ZeroChangeRate();
    void Zero_density();
    void Zero_PhaseGradient(struct Boundary *);
    void Zero_Random();
};
