class Material;
class Interaction;
class Force;
class Particle;
class ParticleManager;
class Initiation;
class Boundary;
class Material;
struct QuinticSpline;
struct Hydrodynamics
{
    int number_of_materials;
    double gravity[2];
    double smoothinglength;
    double delta, delta2, delta3;
    double dt_g_vis, dt_surf;
    IList interaction_list;
    double viscosity_max;
    double  surface_max;
    Material *materials;
    Force **forces;
    List *particle_list;
    Hydrodynamics(Initiation*);
    ~Hydrodynamics();
    double GetTimestep();
    void BuildPair(ParticleManager*, QuinticSpline*);
    void UpdatePair(QuinticSpline*);
    void ZeroChangeRate();
    void AddGravity();
    void UpdateChangeRate(ParticleManager*, QuinticSpline*);
    void UpdateChangeRate();
    void Zero_density();
    void UpdateDensity();
    void UpdatePhaseGradient(Boundary*);
    void Zero_PhaseGradient(Boundary*);
    void UpdateSurfaceStress(Boundary*);
    void UpdatePahseMatrix(Boundary*);
    void UpdateState();
    void Predictor_summation(double dt);
    void Corrector_summation(double dt);
    void Zero_Random();
    void UpdateRandom(double sqrtdt);
    void RandomEffects();
};
