class Particle;
class Force;
class Initiation;
struct QuinticSpline;
class Interaction {
	Particle *Org;	
	Particle *Dest;	
	Force **frc_ij;	
	int noi; 
	int noj; 
	double mi;
	double rmi;
	double etai;
	double zetai;
	double mj;
	double rmj;
	double etaj;
	double zetaj;
	double rij;
	double rrij;
	double Wij;
	double Fij;
	double Wij2;
	double eij[2]; 
	double shear_rij;
	double bulk_rij; 
public:
	Interaction(Particle*, Particle*, Force**, QuinticSpline*, double dstc);
	void RenewInteraction(QuinticSpline*);
	void SummationDensity();
	void SummationPhaseGradient();
	void UpdateForces();
	void RandomForces(double sqrtdt);
};
